android-12.0.0_r2

diff --git a/external/autotest/site_utils/bootperf-bin/bootperf b/external/autotest/site_utils/bootperf-bin/bootperf
--- a/external/autotest/site_utils/bootperf-bin/bootperf
+++ b/external/autotest/site_utils/bootperf-bin/bootperf
@@ -10,27 +10,8 @@
 # NOTE: This script must be run from inside the chromeos build
 # chroot environment.
 #
-
-# --- BEGIN COMMON.SH BOILERPLATE ---
-# Load common CrOS utilities.  Inside the chroot this file is installed in
-# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
-# location.
-find_common_sh() {
-  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
-  local path
-
-  SCRIPT_ROOT=
-  for path in "${common_paths[@]}"; do
-    if [ -r "${path}/common.sh" ]; then
-      SCRIPT_ROOT=${path}
-      break
-    fi
-  done
-}
-
-find_common_sh
-. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
-# --- END COMMON.SH BOILERPLATE ---
+COMMONSH="/mnt/host/source/src/scripts/common.sh"
+. ${COMMONSH} || (echo "Unable to load ${COMMONSH}" && exit 1)
 
 # TODO(jrbarnette) The log files produced in this script will be
 # stored inside the chroot.  So, from outside the chroot, this
