android-5.1.0_r1

diff --git a/external/chromium_org/build/android/adb_gdb b/external/chromium_org/build/android/adb_gdb
--- a/external/chromium_org/build/android/adb_gdb
+++ b/external/chromium_org/build/android/adb_gdb
@@ -473,14 +473,11 @@ get_ndk_toolchain_prebuilt () {
   local SUBPATH="$3"
   local NAME="$(get_arch_toolchain_prefix $ARCH)"
   local FILE TARGET
-  FILE=$NDK_DIR/toolchains/$NAME-4.8/prebuilt/$SUBPATH
+  FILE=$NDK_DIR/toolchains/$NAME-4.9/prebuilt/$SUBPATH
   if [ ! -f "$FILE" ]; then
-    FILE=$NDK_DIR/toolchains/$NAME-4.9/prebuilt/$SUBPATH
+    FILE=$NDK_DIR/toolchains/$NAME-4.8/prebuilt/$SUBPATH
     if [ ! -f "$FILE" ]; then
-      FILE=$NDK_DIR/toolchains/$NAME-4.6/prebuilt/$SUBPATH
-      if [ ! -f "$FILE" ]; then
-        FILE=
-      fi
+      FILE=
     fi
   fi
   echo "$FILE"
@@ -964,15 +961,35 @@ log "Job control: $(jobs -l)"
 STATE=$(jobs -l | awk '$2 == "'$GDBSERVER_PID'" { print $3; }')
 if [ "$STATE" != "Running" ]; then
   echo "ERROR: GDBServer could not attach to PID $PID!"
-  echo "Failure log (use --verbose for more information):"
-  cat $GDBSERVER_LOG
-  exit 1
+  if [ $(adb_shell su -c getenforce) != "Permissive" ];  then
+    echo "Device mode is Enforcing. Changing Device mode to Permissive "
+    $(adb_shell su -c setenforce 0)
+    if [ $(adb_shell su -c getenforce) != "Permissive" ]; then
+      echo "ERROR: Failed to Change Device mode to Permissive"
+      echo "Failure log (use --verbose for more information):"
+      cat $GDBSERVER_LOG
+      exit 1
+    fi
+  else
+    echo "Failure log (use --verbose for more information):"
+    cat $GDBSERVER_LOG
+    exit 1
+  fi
 fi
 
 # Generate a file containing useful GDB initialization commands
 readonly COMMANDS=$TMPDIR/gdb.init
 log "Generating GDB initialization commands file: $COMMANDS"
 echo -n "" > $COMMANDS
+echo "set print pretty 1" >> $COMMANDS
+echo "python" >> $COMMANDS
+echo "import sys" >> $COMMANDS
+echo "sys.path.insert(0, '$CHROMIUM_SRC/tools/gdb/')" >> $COMMANDS
+echo "try:" >> $COMMANDS
+echo "  import gdb_chrome" >> $COMMANDS
+echo "finally:" >> $COMMANDS
+echo "  sys.path.pop(0)" >> $COMMANDS
+echo "end" >> $COMMANDS
 echo "file $TMPDIR/$GDBEXEC" >> $COMMANDS
 echo "directory $CHROMIUM_SRC" >> $COMMANDS
 echo "set solib-absolute-prefix $PULL_LIBS_DIR" >> $COMMANDS
