android-13.0.0_r3 part 1

diff --git a/external/selinux/policycoreutils/scripts/fixfiles b/external/selinux/policycoreutils/scripts/fixfiles
--- a/external/selinux/policycoreutils/scripts/fixfiles
+++ b/external/selinux/policycoreutils/scripts/fixfiles
@@ -109,9 +109,11 @@ fullFlag=0
 BOOTTIME=""
 VERBOSE="-p"
 FORCEFLAG=""
+THREADS=""
 RPMFILES=""
 PREFC=""
 RESTORE_MODE=""
+BIND_MOUNT_FILESYSTEMS=""
 SETFILES=/sbin/setfiles
 RESTORECON=/sbin/restorecon
 FILESYSTEMSRW=`get_rw_labeled_mounts`
@@ -151,7 +153,7 @@ newer() {
     shift
     LogReadOnly
     for m in `echo $FILESYSTEMSRW`; do
-	find $m -mount -newermt $DATE -print0 2>/dev/null | ${RESTORECON} ${FORCEFLAG} ${VERBOSE} $* -i -0 -f -
+	find $m -mount -newermt $DATE -print0 2>/dev/null | ${RESTORECON} ${FORCEFLAG} ${VERBOSE} ${THREADS} $* -i -0 -f -
     done;
 }
 
@@ -161,7 +163,7 @@ newer() {
 #
 diff_filecontext() {
 EXCLUDEDIRS="`exclude_dirs_from_relabelling`"
-for i in /sys /proc /dev /run /mnt /var/tmp /var/lib/BackupPC /home /tmp /dev; do
+for i in /sys /proc /mnt /var/tmp /var/lib/BackupPC /home /root /tmp; do
     [ -e $i ]  && EXCLUDEDIRS="${EXCLUDEDIRS} -e $i";
 done
 LogExcluded
@@ -174,7 +176,7 @@ if [ -f ${PREFC} -a -x /usr/bin/diff ]; then
 	sed -r -e 's,:s0, ,g' $FC | sort -u | \
 	/usr/bin/diff -b ${PREFCTEMPFILE} - | \
 	    grep '^[<>]'|cut -c3-| grep ^/ | \
-	    egrep -v '(^/home|^/root|^/tmp|^/dev)' |\
+	    egrep -v '(^/home|^/root|^/tmp)' |\
 	sed -r -e 's,[[:blank:]].*,,g' \
 	       -e 's|\(([/[:alnum:]]+)\)\?|{\1,}|g' \
 	       -e 's|([/[:alnum:]])\?|{\1,}|g' \
@@ -195,7 +197,7 @@ if [ -f ${PREFC} -a -x /usr/bin/diff ]; then
 		  esac; \
 	       fi; \
 	    done | \
-	${RESTORECON} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} $* -i -R -f -; \
+	${RESTORECON} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} ${THREADS} $* -i -R -f -; \
 	rm -f ${TEMPFILE} ${PREFCTEMPFILE}
 fi
 }
@@ -233,17 +235,33 @@ LogExcluded
 case "$RESTORE_MODE" in
     RPMFILES)
 	for i in `echo "$RPMFILES" | sed 's/,/ /g'`; do
-	    rpmlist $i | ${RESTORECON} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} $* -i -R -f -
+	    rpmlist $i | ${RESTORECON} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} ${THREADS} $* -i -R -f -
 	done
     ;;
     FILEPATH)
-	${RESTORECON} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} $* -R -- "$FILEPATH"
+	${RESTORECON} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} ${THREADS} $* -R -- "$FILEPATH"
     ;;
     *)
 	if [ -n "${FILESYSTEMSRW}" ]; then
 	    LogReadOnly
 	    echo "${OPTION}ing `echo ${FILESYSTEMSRW}`"
-	    ${SETFILES} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} $* -q ${FC} ${FILESYSTEMSRW}
+
+	    if [ -z "$BIND_MOUNT_FILESYSTEMS" ]; then
+	        ${SETFILES} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} $* -q ${THREADS} ${FC} ${FILESYSTEMSRW}
+	    else
+	        # we bind mount so we can fix the labels of files that have already been
+	        # mounted over
+	        for m in `echo $FILESYSTEMSRW`; do
+	            TMP_MOUNT="$(mktemp -d)"
+	            test -z ${TMP_MOUNT+x} && echo "Unable to find temporary directory!" && exit 1
+
+	            mkdir -p "${TMP_MOUNT}${m}" || exit 1
+	            mount --bind "${m}" "${TMP_MOUNT}${m}" || exit 1
+	            ${SETFILES} ${VERBOSE} ${EXCLUDEDIRS} ${FORCEFLAG} ${THREADS} $* -q ${FC} -r "${TMP_MOUNT}" "${TMP_MOUNT}${m}"
+	            umount "${TMP_MOUNT}${m}" || exit 1
+	            rm -rf "${TMP_MOUNT}" || echo "Error cleaning up."
+	        done;
+	    fi
 	else
 	    echo >&2 "fixfiles: No suitable file systems found"
 	fi
@@ -312,7 +330,9 @@ case "$1" in
 	fi
 	> /.autorelabel || exit $?
 	[ -z "$FORCEFLAG" ] || echo -n "$FORCEFLAG " >> /.autorelabel
-	[ -z "$BOOTTIME" ] || echo -N $BOOTTIME >> /.autorelabel
+	[ -z "$BOOTTIME" ] || echo -n "-N $BOOTTIME " >> /.autorelabel
+	[ -z "$BIND_MOUNT_FILESYSTEMS" ] || echo -n "-M " >> /.autorelabel
+	[ -z "$THREADS" ] || echo -n "$THREADS " >> /.autorelabel
 	# Force full relabel if SELinux is not enabled
 	selinuxenabled || echo -F > /.autorelabel
 	echo "System will relabel on next boot"
@@ -324,17 +344,17 @@ esac
 }
 usage() {
 	echo $"""
-Usage: $0 [-v] [-F] [-f] relabel
+Usage: $0 [-v] [-F] [-M] [-f] [-T nthreads] relabel
 or
-Usage: $0 [-v] [-F] [-B | -N time ] { check | restore | verify }
+Usage: $0 [-v] [-F] [-B | -N time ] [-T nthreads] { check | restore | verify }
 or
-Usage: $0 [-v] [-F] { check | restore | verify } dir/file ...
+Usage: $0 [-v] [-F] [-T nthreads] { check | restore | verify } dir/file ...
 or
-Usage: $0 [-v] [-F] -R rpmpackage[,rpmpackage...] { check | restore | verify }
+Usage: $0 [-v] [-F] [-T nthreads] -R rpmpackage[,rpmpackage...] { check | restore | verify }
 or
-Usage: $0 [-v] [-F] -C PREVIOUS_FILECONTEXT { check | restore | verify }
+Usage: $0 [-v] [-F] [-T nthreads] -C PREVIOUS_FILECONTEXT { check | restore | verify }
 or
-Usage: $0 [-F] [-B] onboot
+Usage: $0 [-F] [-M] [-B] [-T nthreads] onboot
 """
 }
 
@@ -353,7 +373,7 @@ set_restore_mode() {
 }
 
 # See how we were called.
-while getopts "N:BC:FfR:l:v" i; do
+while getopts "N:BC:FfR:l:vMT:" i; do
     case "$i" in
 	B)
 		BOOTTIME=`/bin/who -b | awk '{print $3}'`
@@ -379,11 +399,17 @@ while getopts "N:BC:FfR:l:v" i; do
 		echo "Redirecting output to $OPTARG"
 		exec >>"$OPTARG" 2>&1
 		;;
+	M)
+		BIND_MOUNT_FILESYSTEMS="-M"
+		;;
 	F)
 		FORCEFLAG="-F"
 		;;
 	f)
 		fullFlag=1
+		;;
+	T)
+		THREADS="-T $OPTARG"
 		;;
 	*)
 	    usage
diff --git a/external/toolchain-utils/afdo_tools/update_kernel_afdo b/external/toolchain-utils/afdo_tools/update_kernel_afdo
--- a/external/toolchain-utils/afdo_tools/update_kernel_afdo
+++ b/external/toolchain-utils/afdo_tools/update_kernel_afdo
@@ -5,114 +5,245 @@
 
 # Due to crbug.com/1081332, we need to update AFDO metadata
 # manually. This script performs a few checks and generates a
-# new kernel_afdo.json file, which can then be committed.
+# new kernel_afdo.json file, which can then be submitted.
 #
-# USAGE:
-# toolchain-utils$ ./afdo_tools/update_kernel_afdo
-#
-# The script modifies the JSON file and shows the git diff.
-#
-# If the changes look good, git commit them. Example commit
-# message (from crrev.com/c/2197462):
-#
-#   afdo_metadata: Publish the new kernel profiles
-#
-#   Update chromeos-kernel-3_18 to R84-13080.0-1589189810
-#   Update chromeos-kernel-4_4 to R84-13080.0-1589189726
-#   Update chromeos-kernel-4_14 to R84-13080.0-1589190025
-#   Update chromeos-kernel-4_19 to R84-13080.0-1589189550
-#
-#   BUG=None
-#   TEST=Verified in kernel-release-afdo-verify-orchestrator.
-#
+
+USAGE="
+Usage: $(basename $0) [main|beta|stable|all] [--help]
+
+Description:
+  The script takes one optional argument which is the channel where we want
+to update the kernel afdo and creates a commit (or commits with \"all\"
+channels) in the corresponding branch.
+  No arguments defaults to \"all\".
+  Follow the prompt to submit the changes.
+  NO CLEAN-UP NEEDED. The script ignores any local changes and keeps
+the current branch unchanged.
+"
 
 set -eu
 set -o pipefail
 
-CROS_REPO=https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay
 GS_BASE=gs://chromeos-prebuilt/afdo-job/vetted/kernel
-KVERS="3.18 4.4 4.14 4.19"
-errs=""
-successes=0
+KVERS="4.4 4.14 4.19 5.4"
+failed_channels=""
+# Add skipped chrome branches in ascending order here.
+SKIPPED_BRANCHES="95"
 
 script_dir=$(dirname "$0")
-tc_utils_dir="$script_dir/.."
-metadata_dir="$tc_utils_dir/afdo_metadata"
-outfile="$metadata_dir/kernel_afdo.json"
+tc_utils_dir="${script_dir}/.."
+metadata_dir="${tc_utils_dir}/afdo_metadata"
+outfile="$(realpath --relative-to="${tc_utils_dir}" \
+  "${metadata_dir}"/kernel_afdo.json)"
+# Convert toolchain_utils into the absolute path.
+abs_tc_utils_dir="$(realpath ${tc_utils_dir})"
 
-# The most recent Monday, in Unix timestamp format.
-if [ $(date +%a) = "Mon" ]
-then
-  expected_time=$(date +%s -d 00:00:00)
-else
-  expected_time=$(date +%s -d "last Monday")
-fi
+# Check profiles uploaded within the last week.
+expected_time=$(date +%s -d "week ago")
 
-# Get the current canary branch number (using beta + 1)
-beta=$(git ls-remote -h $CROS_REPO | \
-       sed -n -e "s/^.*release-R\([0-9][0-9]*\).*$/\1/p" | \
-       sort -g | tail -1)
-canary="$(($beta + 1))"
+declare -A branch branch_number commit
+remote_repo=$(git -C "${tc_utils_dir}" remote)
+canary_ref="refs/heads/main"
+# Read the last two release-Rxx from remote branches
+# and assign them to stable_ref and beta_ref.
+# sort -V is the version sort which puts R100 after R99.
+last_branches=$(git -C "${tc_utils_dir}" ls-remote -h "${remote_repo}" \
+  release-R\* | cut -f2 | sort -V | tail -n 2)
+# We need `echo` to convert newlines into spaces for read.
+read stable_ref beta_ref <<< $(echo ${last_branches})
+# Branch names which start from release-R.
+branch["beta"]=${beta_ref##*/}
+branch["stable"]=${stable_ref##*/}
+branch["canary"]=${canary_ref##*/}
 
-json="{"
-sep=""
-for kver in $KVERS
+# Get current branch numbers (number which goes after R).
+branch_number["stable"]=$(echo "${branch["stable"]}" | \
+  sed -n -e "s/^release-R\([0-9][0-9]*\).*$/\1/p")
+branch_number["beta"]=$(echo "${branch["beta"]}" | \
+  sed -n -e "s/^release-R\([0-9][0-9]*\).*$/\1/p")
+branch_number["canary"]="$((branch_number[beta] + 1))"
+for skipped_branch in $SKIPPED_BRANCHES ; do
+  if [[ ${branch_number["canary"]} == $skipped_branch ]] ; then
+    ((branch_number[canary]++))
+  fi
+done
+
+# Without arguments the script updates all branches.
+channels=${1:-"all"}
+case "${channels}" in
+  stable | canary | beta )
+    ;;
+  main )
+    channels="canary"
+    ;;
+  all )
+    channels="canary beta stable"
+    ;;
+  --help | help | -h )
+    echo "$USAGE"
+    exit 0
+    ;;
+  * )
+    echo "Channel \"${channels}\" is not supported.
+Must be main (or canary), beta, stable or all." >&2
+    echo "$USAGE"
+    exit 1
+esac
+
+# Fetch latest branches.
+git -C "${tc_utils_dir}" fetch "${remote_repo}"
+
+worktree_dir=$(mktemp -d)
+echo "-> Working in ${worktree_dir}"
+# Create a worktree and make changes there.
+# This way we don't need to clean-up and sync toolchain_utils before the
+# change. Neither we should care about clean-up after the submit.
+git -C "${tc_utils_dir}" worktree add --detach "${worktree_dir}"
+trap "git -C ${abs_tc_utils_dir} worktree remove ${worktree_dir}" EXIT
+cd "${worktree_dir}"
+
+for channel in ${channels}
 do
-  # Sort the gs output by timestamp (default ordering is by name, so
-  # R86-13310.3-1594633089.gcov.xz goes after R86-13310.18-1595237847.gcov.xz)
-  latest=$(gsutil.py ls -l "$GS_BASE/$kver/" | sort -k2 | \
-           grep "R${canary}" | tail -1 || true)
-  if [ -z "$latest" ]
-  then
-    # if no profiles exist for R${canary}, try the previous branch
+  errs=""
+  successes=0
+  curr_branch_number=${branch_number[${channel}]}
+  curr_branch=${branch[${channel}]}
+  echo
+  echo "Checking \"${channel}\" channel..."
+  echo "branch_number=${curr_branch_number} branch=${curr_branch}"
+  json="{"
+  sep=""
+  for kver in $KVERS
+  do
+    # Sort the gs output by timestamp (default ordering is by name, so
+    # R86-13310.3-1594633089.gcov.xz goes after R86-13310.18-1595237847.gcov.xz)
     latest=$(gsutil.py ls -l "$GS_BASE/$kver/" | sort -k2 | \
-             grep "R${beta}" | tail -1)
-  fi
+             grep "R${curr_branch_number}" | tail -1 || true)
+    if [[ -z "$latest" && "${channel}" != "stable" ]]
+    then
+      # if no profiles exist for the current branch, try the previous branch
+      latest=$(gsutil.py ls -l "$GS_BASE/$kver/" | sort -k2 | \
+        grep "R$((curr_branch_number - 1))" | tail -1)
+    fi
 
-  # Verify that the file has the expected date.
-  file_time=$(echo "$latest" | awk '{print $2}')
-  file_time_unix=$(date +%s -d "$file_time")
-  if [ $file_time_unix -lt $expected_time ]
-  then
-    expected=$(env TZ=UTC date +%Y-%m-%dT%H:%M:%SZ -d @$expected_time)
-    echo "Wrong date for $kver: $file_time is before $expected" >&2
-    errs="$errs $kver"
-    continue
-  fi
+    # Verify that the file has the expected date.
+    file_time=$(echo "$latest" | awk '{print $2}')
+    file_time_unix=$(date +%s -d "$file_time")
+    if [ $file_time_unix -lt $expected_time ]
+    then
+      expected=$(env TZ=UTC date +%Y-%m-%dT%H:%M:%SZ -d @$expected_time)
+      echo "Wrong date for $kver: $file_time is before $expected" >&2
+      errs="$errs $kver"
+      continue
+    fi
 
-  # Generate JSON.
-  json_kver=$(echo "$kver" | tr . _)
-  # b/147370213 (migrating profiles from gcov format) may result in the
-  # pattern below no longer doing the right thing.
-  name=$(echo "$latest" | sed 's%.*/\(.*\)\.gcov.*%\1%')
-  json=$(cat <<EOT
+    # Generate JSON.
+    json_kver=$(echo "$kver" | tr . _)
+    # b/147370213 (migrating profiles from gcov format) may result in the
+    # pattern below no longer doing the right thing.
+    name=$(echo "$latest" | sed 's%.*/\(.*\)\.gcov.*%\1%')
+    json=$(cat <<EOT
 $json$sep
     "chromeos-kernel-$json_kver": {
         "name": "$name"
     }
 EOT
-)
-  sep=","
-  successes=$((successes + 1))
+    )
+    sep=","
+    successes=$((successes + 1))
+  done
+
+  # If we did not succeed for any kvers, exit now.
+  if [[ $successes -eq 0 ]]
+  then
+    echo "error: AFDO profiles out of date for all kernel versions" >&2
+    failed_channels="${failed_channels} ${channel}"
+    continue
+  fi
+
+  git reset --hard HEAD
+  echo git checkout "${remote_repo}/${curr_branch}"
+  git checkout "${remote_repo}/${curr_branch}"
+
+  # Write new JSON file.
+  # Don't use `echo` since `json` might have esc characters in it.
+  printf "%s\n}\n" "$json" > "$outfile"
+
+  # If no changes were made, say so.
+  outdir=$(dirname "$outfile")
+  shortstat=$(cd "$outdir" && git status --short $(basename "$outfile"))
+  [ -z "$shortstat" ] && echo $(basename "$outfile")" is up to date." \
+    && continue
+
+  # If we had any errors, warn about them.
+  if [[ -n "$errs" ]]
+  then
+    echo "warning: failed to update $errs in ${channel}" >&2
+    failed_channels="${failed_channels} ${channel}"
+    continue
+  fi
+
+  git add afdo_metadata/kernel_afdo.json
+  case "${channel}" in
+    canary )
+      commit_contents="afdo_metadata: Publish the new kernel profiles
+
+Update chromeos-kernel-4_4
+Update chromeos-kernel-4_14
+Update chromeos-kernel-4_19
+Update chromeos-kernel-5_4
+
+BUG=None
+TEST=Verified in kernel-release-afdo-verify-orchestrator"
+      ;;
+    beta | stable )
+      commit_contents="afdo_metadata: Publish the new kernel profiles\
+ in ${curr_branch}
+
+Have PM pre-approval because this shouldn't break the release branch.
+
+BUG=None
+TEST=Verified in kernel-release-afdo-verify-orchestrator"
+      ;;
+    * )
+      echo "internal error: unhandled channel \"${channel}\"" >&2
+      exit 2
+  esac
+
+  git commit -v -e -m "${commit_contents}"
+
+  commit[${channel}]=$(git -C "${worktree_dir}" rev-parse HEAD)
 done
 
-# If we did not succeed for any kvers, exit now.
-if [ $successes -eq 0 ]
+echo
+# Array size check doesn't play well with the unbound variable option.
+set +u
+if [[ ${#commit[@]} -gt 0 ]]
 then
-  echo "error: AFDO profiles out of date for all kernel versions" >&2
-  exit 2
+  set -u
+  echo "The change is applied in ${!commit[@]}."
+  echo "Run these commands to submit the change:"
+  echo
+  for channel in ${!commit[@]}
+  do
+    echo -e "\tgit -C ${tc_utils_dir} push ${remote_repo} \
+${commit[${channel}]}:refs/for/${branch[${channel}]}"
+  done
+
+  # Report failed channels.
+  if [[ -n "${failed_channels}" ]]
+  then
+    echo
+    echo "error: failed to update kernel afdo in ${failed_channels}" >&2
+    exit 3
+  fi
+else
+  # No commits. Check if it is due to failures.
+  if [[ -z "${failed_channels}" ]]
+  then
+    echo "No changes are applied. It looks like AFDO versions are up to date."
+  else
+    echo "error: update in ${failed_channels} failed" >&2
+    exit 3
+  fi
 fi
-
-# Write new JSON file.
-printf "%s\n}\n" "$json" > "$outfile"
-
-# Show the changes.
-(cd "$tc_utils_dir" && git diff)
-
-# If no changes were made, say so.
-outdir=$(dirname "$outfile")
-shortstat=$(cd "$outdir" && git status --short $(basename "$outfile"))
-[ -n "$shortstat" ] || echo $(basename "$outfile")" is up to date."
-
-# If we had any errors, warn about them.
-[ -z "$errs" ] || echo "warning: failed to update$errs" >&2
