android-13.0.0_r3 part 5

diff --git a/system/media/camera/docs/metadata-generate b/system/media/camera/docs/metadata-generate
--- a/system/media/camera/docs/metadata-generate
+++ b/system/media/camera/docs/metadata-generate
@@ -37,11 +37,12 @@ thisdir=$(cd "$(dirname "$0")"; pwd)
 fwkdir="$ANDROID_BUILD_TOP/frameworks/base/core/java/android/hardware/camera2/"
 fwkdir_html="$ANDROID_BUILD_TOP/frameworks/base/docs/html/reference"
 ndkdir_html="$ANDROID_BUILD_TOP/frameworks/native/docs"
-hidldir="$ANDROID_BUILD_TOP/hardware/interfaces/camera/metadata"
+aidldir="$ANDROID_BUILD_TOP/hardware/interfaces/camera/metadata/aidl/android/hardware/camera/metadata"
 ctsdir="$ANDROID_BUILD_TOP/cts/tests/camera/src/android/hardware/camera2/cts"
 outdir="$ANDROID_PRODUCT_OUT/obj/ETC/system-media-camera-docs_intermediates"
 ndk_header_dir="$ANDROID_BUILD_TOP/frameworks/av/camera/ndk/include/camera"
 ndk_impl_dir="$ANDROID_BUILD_TOP/frameworks/av/camera/ndk/impl"
+libcameraservice_hidl_dir="$ANDROID_BUILD_TOP/frameworks/av/services/camera/libcameraservice/hidl"
 device_info_dir="$ANDROID_BUILD_TOP/cts/tools/cts-device-info/"`
         `"src/com/android/cts/deviceinfo"
 out_files=()
@@ -63,11 +64,10 @@ function gen_file_abs() {
     local in="$1"
     local out="$2"
     local intermediates="$3"
-    local hal_version="${4:-3.2}"
-    local copyright_year="${5:-2021}"
+    local copyright_year="${4:-2022}"
     local spec_file=$thisdir/metadata_definitions.xml
 
-    python3 $thisdir/metadata_parser_xml.py $spec_file $in $out $hal_version $copyright_year
+    python3 $thisdir/metadata_parser_xml.py $spec_file $in $out $copyright_year
 
     local succ=$?
 
@@ -79,6 +79,30 @@ function gen_file_abs() {
         fi
     else
         echo "FAIL: Errors while generating $(relpath "$out")" >& 2
+    fi
+
+    return $succ
+}
+
+function gen_enum_files() {
+    local in="$1"
+    local out_dir="$2"
+    local intermediates="$3"
+    local copyright_year="${4:-2022}"
+    local spec_file=$thisdir/metadata_definitions.xml
+
+    python3 $thisdir/metadata_enums.py $spec_file $in $out_dir $copyright_year
+
+    local succ=$?
+
+    if [[ $succ -eq 0 ]]
+    then
+        echo "OK: Generated enum files in $(relpath "$out_dir")" >& 2
+        if [[ "$intermediates" != "no" ]]; then
+          out_files+=$'\n'" $out_dir/*.aidl"
+        fi
+    else
+        echo "FAIL: Errors while generating enum aidl files in $(relpath "$out_dir")" >& 2
     fi
 
     return $succ
@@ -195,26 +219,23 @@ $thisdir/metadata-check-dependencies || exit 1
 $thisdir/metadata-validate $thisdir/metadata_definitions.xml || exit 1
 $thisdir/metadata-parser-validity-check || exit 1
 
+# Generate AIDL metadata modules
+mkdir -p "${aidldir}"
+gen_file_abs aidl/CameraMetadataSection.mako "$aidldir/CameraMetadataSection.aidl" yes || exit 1
+gen_file_abs aidl/CameraMetadataSectionStart.mako "$aidldir/CameraMetadataSectionStart.aidl" yes || exit 1
+gen_file_abs aidl/CameraMetadataTag.mako "$aidldir/CameraMetadataTag.aidl" yes || exit 1
+gen_enum_files aidl/CameraMetadataEnum.mako "$aidldir" yes || exit 1
+
 # Generate HTML properties documentation
 gen_file html.mako docs.html || exit 1
 
 # Generate C API headers and implementation
 gen_file camera_metadata_tag_info.mako ../src/camera_metadata_tag_info.c || exit 1
 gen_file camera_metadata_tags.mako ../include/system/camera_metadata_tags.h || exit 1
+gen_file camera_metadata_asserts.mako ../src/camera_metadata_asserts.cpp || exit 1
 
-# Generate HIDL metadata modules - new versions need to be added here manually
-mkdir -p "${hidldir}/3.2"
-gen_file_abs HidlMetadata.mako "$hidldir/3.2/types.hal" yes 3.2 2017 || exit 1
-mkdir -p "${hidldir}/3.3"
-gen_file_abs HidlMetadata.mako "$hidldir/3.3/types.hal" yes 3.3 2017 || exit 1
-mkdir -p "${hidldir}/3.4"
-gen_file_abs HidlMetadata.mako "$hidldir/3.4/types.hal" yes 3.4 2017 || exit 1
-mkdir -p "${hidldir}/3.5"
-gen_file_abs HidlMetadata.mako "$hidldir/3.5/types.hal" yes 3.5 2017 || exit 1
-mkdir -p "${hidldir}/3.6"
-gen_file_abs HidlMetadata.mako "$hidldir/3.6/types.hal" yes 3.6 2021 || exit 1
-mkdir -p "${hidldir}/3.7"
-gen_file_abs HidlMetadata.mako "$hidldir/3.7/types.hal" yes 3.7 2021 || exit 1
+#Generate tags with vndk versions for filtering
+gen_file_abs vndk_camera_metadata_tags.mako "$libcameraservice_hidl_dir/VndkVersionMetadataTags.h" yes || exit 1
 
 #Generate NDK header
 gen_file_abs ndk_camera_metadata_tags.mako "$ndk_header_dir/NdkCameraMetadataTags.h" yes || exit 1
