android-12.0.0_r2 part 5

diff --git a/art/test/run-test b/art/test/run-test
--- a/art/test/run-test
+++ b/art/test/run-test
@@ -122,10 +122,13 @@ chroot=
 info="info.txt"
 build="build"
 run="run"
-expected="expected.txt"
+expected_stdout="expected-stdout.txt"
+expected_stderr="expected-stderr.txt"
 check_cmd="check"
-output="output.txt"
-build_output="build-output.txt"
+test_stdout="test-stdout.txt"
+test_stderr="test-stderr.txt"
+build_stdout="build-stdout.txt"
+build_stderr="build-stderr.txt"
 cfg_output="graph.cfg"
 strace_output="strace-output.txt"
 lib="libartd.so"
@@ -352,6 +355,9 @@ while true; do
     elif [ "x$1" = "x--no-precise" ]; then
         run_args+=(--no-precise)
         shift
+    elif [ "x$1" = "x--external-log-tags" ]; then
+        run_args+=(--external-log-tags)
+        shift
     elif [ "x$1" = "x--invoke-with" ]; then
         shift
         what="$1"
@@ -557,7 +563,7 @@ function err_echo() {
 # Cannot use readlink -m, as it does not exist on Mac.
 # Fallback to nuclear option:
 noncanonical_tmp_dir=$tmp_dir
-tmp_dir="`cd $oldwd ; python -c "import os; import sys; sys.stdout.write(os.path.realpath('$tmp_dir'))"`"
+tmp_dir="`cd $oldwd ; python3 -c "import os; import sys; sys.stdout.write(os.path.realpath('$tmp_dir'))"`"
 if [ -z $tmp_dir ] ; then
   err_echo "Failed to resolve $tmp_dir"
   exit 1
@@ -615,7 +621,8 @@ fi
 function guess_target_arch_name() {
     # Check whether this is a device with native bridge. Currently this is hardcoded
     # to x86 + arm.
-    x86_arm=`ls ${ANDROID_PRODUCT_OUT}/data/art-test | sort | grep -E '^(arm|x86)$'`
+    local guess_path=${ANDROID_PRODUCT_OUT}/system/apex/com.android.art.testing/javalib
+    local x86_arm=`ls ${guess_path} | sort | grep -E '^(arm|x86)$'`
     # Collapse line-breaks into spaces
     x86_arm=$(echo $x86_arm)
     if [ "x$x86_arm" = "xarm x86" ] ; then
@@ -627,8 +634,8 @@ function guess_target_arch_name() {
             target_arch_name=x86
         fi
     else
-        grep32bit=`ls ${ANDROID_PRODUCT_OUT}/data/art-test | grep -E '^(arm|x86)$'`
-        grep64bit=`ls ${ANDROID_PRODUCT_OUT}/data/art-test | grep -E '^(arm64|x86_64)$'`
+        local grep32bit=`ls ${guess_path} | grep -E '^(arm|x86)$'`
+        local grep64bit=`ls ${guess_path} | grep -E '^(arm64|x86_64)$'`
         if [ "x${suffix64}" = "x64" ]; then
             target_arch_name=${grep64bit}
         else
@@ -675,12 +682,16 @@ if [ "$runtime" = "dalvik" ]; then
 elif [ "$runtime" = "art" ]; then
     if [ "$target_mode" = "no" ]; then
         guess_host_arch_name
-        run_args+=(--boot "${ANDROID_HOST_OUT}/framework/core.art:*")
+        run_args+=(--boot "${ANDROID_HOST_OUT}/apex/art_boot_images/javalib/boot.art")
         run_args+=(--runtime-option "-Djava.library.path=${host_lib_root}/lib${suffix64}:${host_lib_root}/nativetest${suffix64}")
     else
         guess_target_arch_name
+        # Note that libarttest(d).so and other test libraries that depend on ART
+        # internal libraries must not be in this path for JNI libraries - they
+        # need to be loaded through LD_LIBRARY_PATH and
+        # NATIVELOADER_DEFAULT_NAMESPACE_LIBS instead.
         run_args+=(--runtime-option "-Djava.library.path=/data/nativetest${suffix64}/art/${target_arch_name}")
-        run_args+=(--boot "/data/art-test/core.art:/data/art-test/*")
+        run_args+=(--boot "/apex/com.android.art/javalib/boot.art")
     fi
     if [ "$relocate" = "yes" ]; then
       run_args+=(--relocate)
@@ -760,7 +771,7 @@ if [ "$usage" = "yes" ]; then
         echo "              The script will only run the test portion, and " \
              "share oat and dex files."
         echo "  $prog --update [options] [test-name]  Update mode" \
-             "(replaces expected.txt)."
+             "(replaces expected-stdout.txt and expected-stderr.txt)."
         echo '  Omitting the test name or specifying "-" will use the' \
              "current directory."
         echo "  Runtime Options:"
@@ -797,7 +808,6 @@ if [ "$usage" = "yes" ]; then
         echo "    --zygote              Spawn the process from the Zygote." \
              "If used, then the"
         echo "                          other runtime options are ignored."
-        echo "    --no-dex2oat          Run as though dex2oat was failing."
         echo "    --prebuild            Run dex2oat on the files before starting test. (default)"
         echo "    --no-prebuild         Do not run dex2oat on the files before starting"
         echo "                          the test."
@@ -851,6 +861,8 @@ if [ "$usage" = "yes" ]; then
         echo "    --instruction-set-features [string]"
         echo "                          Set instruction-set-features for compilation."
         echo "    --quiet               Don't print anything except failure messages"
+        echo "    --external-log-tags   Use ANDROID_LOG_TAGS to set a custom logging level for"
+        echo "                          a test run."
         echo "    --bisection-search    Perform bisection bug search."
         echo "    --vdex                Test using vdex as in input to dex2oat. Only works with --prebuild."
         echo "    --suspend-timeout     Change thread suspend timeout ms (default 500000)."
@@ -863,17 +875,15 @@ cd "$test_dir"
 test_dir=`pwd`
 
 td_info="${test_dir}/${info}"
-td_expected="${test_dir}/${expected}"
+td_expected_stdout="${test_dir}/${expected_stdout}"
+td_expected_stderr="${test_dir}/${expected_stderr}"
 
-if [ ! -r $td_info ]; then
-    err_echo "${test_dir}: missing file $td_info"
-    exit 1
-fi
-
-if [ ! -r $td_expected ]; then
-    err_echo "${test_dir}: missing file $td_expected"
-    exit 1
-fi
+for td_file in "$td_info" "$td_expected_stdout" "$td_expected_stderr"; do
+    if [ ! -r "$td_file" ]; then
+        err_echo "${test_dir}: missing file $td_file"
+        exit 1
+    fi
+done
 
 # copy the test to a temp dir and run it
 
@@ -928,6 +938,7 @@ if [[ "$TEST_NAME" =~ ^[0-9]+-checker- ]]; then
       fi
 
       run_args+=(-Xcompiler-option "--dump-cfg=$cfg_output_dir/$cfg_output" -Xcompiler-option -j1)
+      checker_args="$checker_args --print-cfg"
     fi
   fi
 fi
@@ -959,12 +970,12 @@ good_build="yes"
 good_run="yes"
 export TEST_RUNTIME="${runtime}"
 if [ "$dev_mode" = "yes" ]; then
-    "./${build}" $build_args 2>&1
+    "./${build}" $build_args
     build_exit="$?"
     echo "build exit status: $build_exit" 1>&2
     if [ "$build_exit" = '0' ]; then
         echo "${test_dir}: running..." 1>&2
-        "./${run}" "${run_args[@]}" "$@" 2>&1
+        "./${run}" "${run_args[@]}" "$@"
         run_exit="$?"
 
         if [ "$run_exit" = "0" ]; then
@@ -985,45 +996,61 @@ if [ "$dev_mode" = "yes" ]; then
         echo "run exit status: $run_exit" 1>&2
     fi
 elif [ "$update_mode" = "yes" ]; then
-    "./${build}" $build_args >"$build_output" 2>&1
+    "./${build}" $build_args >"$build_stdout" 2>"$build_stderr"
     build_exit="$?"
     if [ "$build_exit" = '0' ]; then
         echo "${test_dir}: running..." 1>&2
-        "./${run}" "${run_args[@]}" "$@" >"$output" 2>&1
+        "./${run}" "${run_args[@]}" "$@" >"$test_stdout" 2>"$test_stderr"
         if [ "$run_checker" = "yes" ]; then
           if [ "$target_mode" = "yes" ]; then
             adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
           fi
-          "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >> "$output" 2>&1
+          "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >>"$test_stdout" 2>>"$test_stderr"
         fi
-        sed -e 's/[[:cntrl:]]$//g' < "$output" >"${td_expected}"
+        sed -e 's/[[:cntrl:]]$//g' <"$test_stdout" >"${td_expected_stdout}"
+        sed -e 's/[[:cntrl:]]$//g' <"$test_stderr" >"${td_expected_stderr}"
         good="yes"
     else
-        cat "$build_output" 1>&${real_stderr} 1>&2
+        err_echo "#################### build standard output"
+        cat "$build_stdout" 1>&${real_stderr}
+        err_echo "####################"
+        err_echo "#################### build standard error"
+        cat "$build_stderr" 1>&${real_stderr}
+        err_echo "####################"
         err_echo "build exit status: $build_exit"
     fi
 elif [ "$build_only" = "yes" ]; then
     good="yes"
-    "./${build}" $build_args >"$build_output" 2>&1
+    "./${build}" $build_args >"$build_stdout" 2>"$build_stderr"
     build_exit="$?"
     if [ "$build_exit" '!=' '0' ]; then
-        cp "$build_output" "$output"
-        echo "build exit status: $build_exit" >>"$output"
-        diff --strip-trailing-cr -q "$expected" "$output" >/dev/null
+        cp "$build_stdout" "$test_stdout"
+        diff --strip-trailing-cr -q "$expected_stdout" "$test_stdout" >/dev/null
         if [ "$?" '!=' "0" ]; then
             good="no"
-            err_echo "BUILD FAILED For ${TEST_NAME}"
+            err_echo "BUILD FAILED For ${TEST_NAME}" \
+              "(the build's standard output does not match the expected standard output)"
         fi
+        cp "$build_stderr" "$test_stderr"
+        diff --strip-trailing-cr -q "$expected_stderr" "$test_stderr" >/dev/null
+        if [ "$?" '!=' "0" ]; then
+            good="no"
+            err_echo "BUILD FAILED For ${TEST_NAME}" \
+              "(the build's standard error does not match the expected standard error)"
+        fi
+        echo "build exit status: $build_exit" >>"$test_stderr"
     fi
     # Clean up extraneous files that are not used by tests.
-    find $tmp_dir -mindepth 1  ! -regex ".*/\(.*jar\|$output\|$expected\)" | xargs rm -rf
+    find $tmp_dir -mindepth 1  \
+        ! -regex ".*/\(.*jar\|$test_stdout\|$expected_stdout|$test_stderr\|$expected_stderr\)" \
+      | xargs rm -rf
     exit 0
 else
-    "./${build}" $build_args >"$build_output" 2>&1
+    "./${build}" $build_args >"$build_stdout" 2>"$build_stderr"
     build_exit="$?"
     if [ "$build_exit" = '0' ]; then
         echo "${test_dir}: running..." 1>&2
-        "./${run}" "${run_args[@]}" "$@" >"$output" 2>&1
+        "./${run}" "${run_args[@]}" "$@" >"$test_stdout" 2>"$test_stderr"
         run_exit="$?"
         if [ "$run_exit" != "0" ]; then
             err_echo "run exit status: $run_exit"
@@ -1032,7 +1059,7 @@ else
             if [ "$target_mode" = "yes" ]; then
               adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
             fi
-            "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >> "$output" 2>&1
+            "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >>"$test_stdout" 2>>"$test_stderr"
             checker_exit="$?"
             if [ "$checker_exit" != "0" ]; then
                 err_echo "checker exit status: $checker_exit"
@@ -1045,20 +1072,22 @@ else
         fi
     else
         good_build="no"
-        cp "$build_output" "$output"
-        echo "Failed to build in tmpdir=${tmp_dir} from oldwd=${oldwd} and cwd=`pwd`" >> "$output"
-        echo "Non-canonical tmpdir was ${noncanonical_tmp_dir}" >> "$output"
-        echo "Args: ${args}" >> "$output"
-        echo "build exit status: $build_exit" >> "$output"
+        cp "$build_stdout" "$test_stdout"
+        cp "$build_stderr" "$test_stderr"
+        echo "Failed to build in tmpdir=${tmp_dir} from oldwd=${oldwd} and cwd=`pwd`" \
+          >> "$test_stderr"
+        echo "Non-canonical tmpdir was ${noncanonical_tmp_dir}" >> "$test_stderr"
+        echo "Args: ${args}" >> "$test_stderr"
+        echo "build exit status: $build_exit" >> "$test_stderr"
         max_name_length=$(getconf NAME_MAX ${tmp_dir})
-        echo "Max filename (NAME_MAX): ${max_name_length}" >> "$output"
+        echo "Max filename (NAME_MAX): ${max_name_length}" >> "$test_stderr"
         max_path_length=$(getconf PATH_MAX ${tmp_dir})
-        echo "Max pathlength (PATH_MAX): ${max_path_length}" >> "$output"
+        echo "Max pathlength (PATH_MAX): ${max_path_length}" >> "$test_stderr"
     fi
-    ./$check_cmd "$expected" "$output"
+    ./$check_cmd "$expected_stdout" "$test_stdout" "$expected_stderr" "$test_stderr"
     if [ "$?" = "0" ]; then
         if [ "$good_build" = "no" -o "$good_run" = "yes" ]; then
-          # output == expected
+          # test_stdout == expected_stdout && test_stderr == expected_stderr
           good="yes"
           echo "${test_dir}: succeeded!" 1>&2
         fi
@@ -1071,13 +1100,16 @@ fi
         echo ' '
         echo '#################### info'
         cat "${td_info}" | sed 's/^/# /g'
-        echo '#################### diffs'
+        echo '#################### stdout diffs'
         if [ "$run_checker" == "yes" ]; then
           # Checker failures dump the whole CFG, so we output the whole diff.
-          diff --strip-trailing-cr -u "$expected" "$output"
+          diff --strip-trailing-cr -u "$expected_stdout" "$test_stdout"
         else
-          diff --strip-trailing-cr -u "$expected" "$output" | tail -n 3000
+          diff --strip-trailing-cr -u "$expected_stdout" "$test_stdout" | tail -n 10000
         fi
+        echo '####################'
+        echo '#################### stderr diffs'
+        diff --strip-trailing-cr -u "$expected_stderr" "$test_stderr" | tail -n 10000
         echo '####################'
         if [ "$strace" = "yes" ]; then
             echo '#################### strace output'
@@ -1087,7 +1119,8 @@ fi
         if [ "x$target_mode" = "xno" -a "x$SANITIZE_HOST" = "xaddress" ]; then
             # Run the stack script to symbolize any ASAN aborts on the host for SANITIZE_HOST. The
             # tools used by the given ABI work for both x86 and x86-64.
-            echo "ABI: 'x86_64'" | cat - "$output" | $ANDROID_BUILD_TOP/development/scripts/stack | tail -n 3000
+            echo "ABI: 'x86_64'" | cat - "$test_stdout" "$test_stderr" \
+              | $ANDROID_BUILD_TOP/development/scripts/stack | tail -n 3000
         fi
         echo ' '
     fi
@@ -1123,7 +1156,7 @@ if [ "$bisection_search" = "yes" -a "$good" != "yes" ]; then
         $maybe_device_mode \
         --raw-cmd="$raw_cmd" \
         --check-script="$cwd/check" \
-        --expected-output="$cwd/expected.txt" \
+        --expected-output="$cwd/expected-stdout.txt" \
         --logfile="$cwd/bisection_log.txt" \
         --timeout=${timeout:-300}
     fi
diff --git a/system/update_engine/scripts/brillo_update_payload b/system/update_engine/scripts/brillo_update_payload
--- a/system/update_engine/scripts/brillo_update_payload
+++ b/system/update_engine/scripts/brillo_update_payload
@@ -89,12 +89,14 @@ die() {
   exit 1
 }
 
-# Loads shflags. We first look at the default install location; then look for
-# crosutils (chroot); finally check our own directory.
+# Loads shflags. We first look at the default install location; then our own
+# directory; finally the parent directory.
 load_shflags() {
   local my_dir="$(dirname "$(readlink -f "$0")")"
   local path
-  for path in /usr/share/misc "${my_dir}"/lib/shflags; do
+  for path in /usr/share/misc \
+    "${my_dir}"/lib/shflags \
+    "${my_dir}"/../lib/shflags; do
     if [[ -r "${path}/shflags" ]]; then
       . "${path}/shflags" || die "Could not load ${path}/shflags."
       return
@@ -186,9 +188,22 @@ if [[ "${COMMAND}" == "generate" ]]; then
     "Optional: The maximum unix timestamp of the OS allowed to apply this \
 payload, should be set to a number higher than the build timestamp of the \
 system running on the device, 0 if not specified."
+  DEFINE_string partition_timestamps "" \
+    "Optional: Per-partition maximum unix timestamp of the OS allowed to \
+apply this payload. Should be a comma separated key value pairs. e.x.\
+system:1234,vendor:456"
   DEFINE_string disable_fec_computation "" \
     "Optional: Disables the on device fec data computation for incremental \
 update. This feature is enabled by default."
+  DEFINE_string disable_verity_computation "" \
+    "Optional: Disables the on device verity computation for incremental \
+update. This feature is enabled by default."
+  DEFINE_string is_partial_update "" \
+    "Optional: True if the payload is for partial update. i.e. it only updates \
+a subset of partitions on device."
+  DEFINE_string full_boot "" "Will include full boot image"
+  DEFINE_string disable_vabc "" \
+    "Optional: Disables Virtual AB Compression when installing the OTA"
 fi
 if [[ "${COMMAND}" == "hash" || "${COMMAND}" == "sign" ]]; then
   DEFINE_string unsigned_payload "" "Path to the input unsigned payload."
@@ -270,6 +285,9 @@ POSTINSTALL_CONFIG_FILE=""
 
 # Path to the dynamic partition info file in target image if exists.
 DYNAMIC_PARTITION_INFO_FILE=""
+
+# Path to the META/apex_info.pb found in target build
+APEX_INFO_FILE=""
 
 # read_option_int <file.txt> <option_key> [default_value]
 #
@@ -554,6 +572,13 @@ Disabling deltas for this source version."
         "${dynamic_partitions_info}"
       DYNAMIC_PARTITION_INFO_FILE="${dynamic_partitions_info}"
     fi
+    local apex_info=$(create_tempfile "apex_info.XXXXXX")
+    CLEANUP_FILES+=("${apex_info}")
+    if unzip -l "${image}" "META/apex_info.pb" > /dev/null; then
+      extract_file "${image}" "META/apex_info.pb" \
+        "${apex_info}"
+      APEX_INFO_FILE="${apex_info}"
+    fi
   fi
 
   local part
@@ -642,7 +667,12 @@ cmd_generate() {
     fi
     partition_names+="${part}"
     new_partitions+="${DST_PARTITIONS[${part}]}"
-    old_partitions+="${SRC_PARTITIONS[${part}]:-}"
+    if [ "${FLAGS_full_boot}" == "true" ] && [ "${part}" == "boot" ]; then
+      # Skip boot partition.
+      old_partitions+=""
+    else
+      old_partitions+="${SRC_PARTITIONS[${part}]:-}"
+    fi
     new_mapfiles+="${DST_PARTITIONS_MAP[${part}]:-}"
     old_mapfiles+="${SRC_PARTITIONS_MAP[${part}]:-}"
   done
@@ -654,19 +684,40 @@ cmd_generate() {
     --new_mapfiles="${new_mapfiles}"
   )
 
+  if [[ "${FLAGS_is_partial_update}" == "true" ]]; then
+    GENERATOR_ARGS+=( --is_partial_update="true" )
+    # Need at least minor version 7 for partial update, so generate with minor
+    # version 7 if we don't have a source image. Let the delta_generator to fail
+    # the other incompatiable minor versions.
+    if [[ -z "${FORCE_MINOR_VERSION}" ]]; then
+      FORCE_MINOR_VERSION="7"
+    fi
+  fi
+
   if [[ "${payload_type}" == "delta" ]]; then
     # Source image args:
     GENERATOR_ARGS+=(
       --old_partitions="${old_partitions}"
       --old_mapfiles="${old_mapfiles}"
     )
-    if [[ -n "${FORCE_MINOR_VERSION}" ]]; then
-      GENERATOR_ARGS+=( --minor_version="${FORCE_MINOR_VERSION}" )
-    fi
     if [[ -n "${FLAGS_disable_fec_computation}" ]]; then
       GENERATOR_ARGS+=(
         --disable_fec_computation="${FLAGS_disable_fec_computation}" )
     fi
+    if [[ -n "${FLAGS_disable_verity_computation}" ]]; then
+      GENERATOR_ARGS+=(
+        --disable_verity_computation="${FLAGS_disable_verity_computation}" )
+    fi
+  fi
+
+  if [[ -n "${FLAGS_disable_vabc}" ]]; then
+    GENERATOR_ARGS+=(
+      --disable_vabc="${FLAGS_disable_vabc}" )
+  fi
+
+  # minor version is set only for delta or partial payload.
+  if [[ -n "${FORCE_MINOR_VERSION}" ]]; then
+    GENERATOR_ARGS+=( --minor_version="${FORCE_MINOR_VERSION}" )
   fi
 
   if [[ -n "${FORCE_MAJOR_VERSION}" ]]; then
@@ -681,6 +732,10 @@ cmd_generate() {
     GENERATOR_ARGS+=( --max_timestamp="${FLAGS_max_timestamp}" )
   fi
 
+  if [[ -n "${FLAGS_partition_timestamps}" ]]; then
+    GENERATOR_ARGS+=( --partition_timestamps="${FLAGS_partition_timestamps}" )
+  fi
+
   if [[ -n "${POSTINSTALL_CONFIG_FILE}" ]]; then
     GENERATOR_ARGS+=(
       --new_postinstall_config_file="${POSTINSTALL_CONFIG_FILE}"
@@ -690,6 +745,11 @@ cmd_generate() {
   if [[ -n "{DYNAMIC_PARTITION_INFO_FILE}" ]]; then
     GENERATOR_ARGS+=(
       --dynamic_partition_info_file="${DYNAMIC_PARTITION_INFO_FILE}"
+    )
+  fi
+  if [[ -n "{APEX_INFO_FILE}" ]]; then
+    GENERATOR_ARGS+=(
+      --apex_info_file="${APEX_INFO_FILE}"
     )
   fi
 
@@ -881,8 +941,8 @@ cmd_check() {
   check_update_payload ${PAYCHECK_ARGS[@]} --check
 }
 
-# Sanity check that the real generator exists:
-GENERATOR="$(which delta_generator || true)"
+# Check that the real generator exists:
+[[ -x "${GENERATOR}" ]] || GENERATOR="$(which delta_generator || true)"
 [[ -x "${GENERATOR}" ]] || die "can't find delta_generator"
 
 case "$COMMAND" in
