android-13.0.0_r3

diff --git a/art/test/etc/run-test-jar b/art/test/etc/run-test-jar
--- a/art/test/etc/run-test-jar
+++ b/art/test/etc/run-test-jar
@@ -2,8 +2,27 @@
 #
 # Runner for an individual run-test.
 
+readonly local_path=$(dirname "$0")
+source "${local_path}/apex-bootclasspath-utils.sh"
+
+# Check how many colors the terminal can display.
+ncolors=$(tput colors 2>/dev/null)
+
+# Check that stdout is connected to a terminal and that we have at least 1 color.
+# This ensures that if the stdout is not connected to a terminal and instead
+# the stdout will be used for a log, it will not append the color characters.
+if [[ -t 1 && ${ncolors} && ${ncolors} -ge 1 ]]; then
+  bold_red="$(tput bold)$(tput setaf 1)"
+fi
+
+readonly bold_red
+
+error_msg() {
+  echo -e "${bold_red}ERROR: $@" 1>&2
+}
+
 if [[ -z "$ANDROID_BUILD_TOP" ]]; then
-  echo 'ANDROID_BUILD_TOP environment variable is empty; did you forget to run `lunch`?'
+  error_msg 'ANDROID_BUILD_TOP environment variable is empty; did you forget to run `lunch`?'
   exit 1
 fi
 
@@ -38,6 +57,8 @@ FLAGS=""
 ANDROID_FLAGS=""
 GDB=""
 GDB_ARGS=""
+GDB_DEX2OAT=""
+GDB_DEX2OAT_ARGS=""
 GDBSERVER_DEVICE="gdbserver"
 GDBSERVER_HOST="gdbserver"
 HAVE_IMAGE="y"
@@ -71,6 +92,7 @@ TIME_OUT_VALUE=
 USE_GDB="n"
 USE_GDBSERVER="n"
 GDBSERVER_PORT=":5039"
+USE_GDB_DEX2OAT="n"
 USE_JVM="n"
 USE_JVMTI="n"
 VERIFY="y" # y=yes,n=no,s=softfail
@@ -82,7 +104,8 @@ VDEX_ARGS=""
 EXTERNAL_LOG_TAGS="n" # if y respect externally set ANDROID_LOG_TAGS.
 DRY_RUN="n" # if y prepare to run the test but don't run it.
 TEST_VDEX="n"
-TEST_DM="n"
+TEST_DEX2OAT_DM="n"
+TEST_RUNTIME_DM="n"
 TEST_IS_NDEBUG="n"
 APP_IMAGE="y"
 SECONDARY_APP_IMAGE="y"
@@ -122,7 +145,7 @@ while true; do
     elif [ "x$1" = "x--dex2oat-rt-timeout" ]; then
         shift
         if [ "x$1" = "x" ]; then
-            echo "$0 missing argument to --dex2oat-rt-timeout" 1>&2
+            error_msg "$0 missing argument to --dex2oat-rt-timeout"
             exit 1
         fi
         DEX2OAT_RT_TIMEOUT="$1"
@@ -130,7 +153,7 @@ while true; do
     elif [ "x$1" = "x--dex2oat-timeout" ]; then
         shift
         if [ "x$1" = "x" ]; then
-            echo "$0 missing argument to --dex2oat-timeout" 1>&2
+            error_msg "$0 missing argument to --dex2oat-timeout"
             exit 1
         fi
         DEX2OAT_TIMEOUT="$1"
@@ -150,7 +173,7 @@ while true; do
     elif [ "x$1" = "x--lib" ]; then
         shift
         if [ "x$1" = "x" ]; then
-            echo "$0 missing argument to --lib" 1>&2
+            error_msg "$0 missing argument to --lib"
             exit 1
         fi
         LIB="$1"
@@ -162,7 +185,7 @@ while true; do
     elif [ "x$1" = "x--testlib" ]; then
         shift
         if [ "x$1" = "x" ]; then
-            echo "$0 missing argument to --testlib" 1>&2
+            error_msg "$0 missing argument to --testlib"
             exit 1
         fi
         ARGS="${ARGS} $1"
@@ -170,7 +193,7 @@ while true; do
     elif [ "x$1" = "x--args" ]; then
         shift
         if [ "x$1" = "x" ]; then
-            echo "$0 missing argument to --args" 1>&2
+            error_msg "$0 missing argument to --args"
             exit 1
         fi
         ARGS="${ARGS} $1"
@@ -199,8 +222,7 @@ while true; do
         option="$1"
         FLAGS="${FLAGS} $option"
         if [ "x$option" = "x-Xmethod-trace" ]; then
-            # Method tracing can slow some tests down a lot, in particular
-            # 530-checker-lse2.
+            # Method tracing can slow some tests down a lot.
             TIME_OUT_EXTRA=$((${TIME_OUT_EXTRA} + 1200))
         fi
         shift
@@ -349,6 +371,17 @@ while true; do
         gdb_arg="$1"
         GDB_ARGS="${GDB_ARGS} $gdb_arg"
         shift
+    elif [ "x$1" = "x--gdb-dex2oat" ]; then
+        USE_GDB_DEX2OAT="y"
+        DEV_MODE="y"
+        TIME_OUT="n"
+        shift
+    elif [ "x$1" = "x--gdb-dex2oat-args" ]; then
+        shift
+        for arg in $(echo $1 | tr ";" " "); do
+          GDB_DEX2OAT_ARGS+="$arg "
+        done
+        shift
     elif [ "x$1" = "x--zygote" ]; then
         ZYGOTE="-Xzygote"
         msg "Spawning from zygote"
@@ -372,7 +405,7 @@ while true; do
     elif [ "x$1" = "x--invoke-with" ]; then
         shift
         if [ "x$1" = "x" ]; then
-            echo "$0 missing argument to --invoke-with" 1>&2
+            error_msg "$0 missing argument to --invoke-with"
             exit 1
         fi
         if [ "x$INVOKE_WITH" = "x" ]; then
@@ -393,6 +426,9 @@ while true; do
     elif [ "x$1" = "x--chroot" ]; then
         shift
         CHROOT="$1"
+        shift
+    elif [ "x$1" = "x--simpleperf" ]; then
+        SIMPLEPERF="yes"
         shift
     elif [ "x$1" = "x--android-root" ]; then
         shift
@@ -435,7 +471,7 @@ while true; do
         shift
     elif [ "x$1" = "x--experimental" ]; then
         if [ "$#" -lt 2 ]; then
-            echo "missing --experimental option" 1>&2
+            error_msg "missing --experimental option"
             exit 1
         fi
         EXPERIMENTAL="$EXPERIMENTAL $2"
@@ -449,8 +485,11 @@ while true; do
     elif [ "x$1" = "x--vdex" ]; then
         TEST_VDEX="y"
         shift
-    elif [ "x$1" = "x--dm" ]; then
-        TEST_DM="y"
+    elif [ "x$1" = "x--dex2oat-dm" ]; then
+        TEST_DEX2OAT_DM="y"
+        shift
+    elif [ "x$1" = "x--runtime-dm" ]; then
+        TEST_RUNTIME_DM="y"
         shift
     elif [ "x$1" = "x--vdex-filter" ]; then
         shift
@@ -471,7 +510,7 @@ while true; do
         RANDOM_PROFILE="y"
         shift
     elif expr "x$1" : "x--" >/dev/null 2>&1; then
-        echo "unknown $0 option: $1" 1>&2
+        error_msg "unknown $0 option: $1"
         exit 1
     else
         break
@@ -582,7 +621,7 @@ elif [ "$DEBUGGER" = "agent" ]; then
   PORT=12345
   # TODO Support ddms connection and support target.
   if [ "$HOST" = "n" ]; then
-    echo "--debug-agent not supported yet for target!"
+    error_msg "--debug-agent not supported yet for target!"
     exit 1
   fi
   AGENTPATH=${DEBUGGER_AGENT}
@@ -610,6 +649,12 @@ if [ "$USE_JVMTI" = "y" ]; then
     # We used to add flags here that made the runtime debuggable but that is not
     # needed anymore since the plugin can do it for us now.
     FLAGS="${FLAGS} -Xplugin:${plugin}"
+
+    # For jvmti tests, set the threshold of compilation to 1, so we jit early to
+    # provide better test coverage for jvmti + jit. This means we won't run
+    # the default --jit configuration but it is not too important test scenario for
+    # jvmti tests. This is art specific flag, so don't use it with jvm.
+    FLAGS="${FLAGS} -Xjitthreshold:1"
   fi
 fi
 
@@ -692,43 +737,19 @@ if [ "$USE_JVM" = "y" ]; then
   exit
 fi
 
-# Note: This must start with the CORE_IMG_JARS in Android.common_path.mk
-# because that's what we use for compiling the boot.art image.
-# It may contain additional modules from TEST_CORE_JARS.
-bpath_modules="core-oj core-libart okhttp bouncycastle apache-xml core-icu4j conscrypt"
-bpath=""
-bpath_locations=""
-bpath_separator=""
-bpath_prefix=""
-bpath_location_prefix=""
-if [ "${HOST}" = "y" ]; then
-  bpath_prefix="${ANDROID_HOST_OUT}"
-  if [ "${ANDROID_HOST_OUT:0:${#ANDROID_BUILD_TOP}+1}" = "${ANDROID_BUILD_TOP}/" ]; then
-    bpath_location_prefix="${ANDROID_HOST_OUT:${#ANDROID_BUILD_TOP}+1}"
-  else
-    echo "error: ANDROID_BUILD_TOP/ is not a prefix of ANDROID_HOST_OUT"
-    echo "ANDROID_BUILD_TOP=${ANDROID_BUILD_TOP}"
-    echo "ANDROID_HOST_OUT=${ANDROID_HOST_OUT}"
-    exit
-  fi
+readonly b_path=$(get_apex_bootclasspath ${HOST})
+readonly b_path_locations=$(get_apex_bootclasspath_locations ${HOST})
+
+BCPEX=
+if [ -f "$TEST_NAME-bcpex.jar" ] ; then
+  BCPEX=":$DEX_LOCATION/$TEST_NAME-bcpex.jar"
 fi
-for bpath_module in ${bpath_modules}; do
-  apex_module="com.android.art"
-  case "$bpath_module" in
-    (conscrypt)  apex_module="com.android.conscrypt";;
-    (core-icu4j) apex_module="com.android.i18n";;
-    (*)          apex_module="com.android.art";;
-  esac
-  bpath_jar="/apex/${apex_module}/javalib/${bpath_module}.jar"
-  bpath+="${bpath_separator}${bpath_prefix}${bpath_jar}"
-  bpath_locations+="${bpath_separator}${bpath_location_prefix}${bpath_jar}"
-  bpath_separator=":"
-done
+
 # Pass down the bootclasspath
-FLAGS="${FLAGS} -Xbootclasspath:${bpath}"
-FLAGS="${FLAGS} -Xbootclasspath-locations:${bpath_locations}"
-COMPILE_FLAGS="${COMPILE_FLAGS} --runtime-arg -Xbootclasspath:${bpath}"
-COMPILE_FLAGS="${COMPILE_FLAGS} --runtime-arg -Xbootclasspath-locations:${bpath_locations}"
+FLAGS="${FLAGS} -Xbootclasspath:${b_path}${BCPEX}"
+FLAGS="${FLAGS} -Xbootclasspath-locations:${b_path_locations}${BCPEX}"
+COMPILE_FLAGS="${COMPILE_FLAGS} --runtime-arg -Xbootclasspath:${b_path}"
+COMPILE_FLAGS="${COMPILE_FLAGS} --runtime-arg -Xbootclasspath-locations:${b_path_locations}"
 
 if [ "$HAVE_IMAGE" = "n" ]; then
     # Disable image dex2oat - this will forbid the runtime to patch or compile an image.
@@ -737,19 +758,24 @@ if [ "$HAVE_IMAGE" = "n" ]; then
     # We'll abuse a second flag here to test different behavior. If --relocate, use the
     # existing image - relocation will fail as patching is disallowed. If --no-relocate,
     # pass a non-existent image - compilation will fail as dex2oat is disallowed.
-    if [ "${RELOCATE}" = "y" ] ; then
-      DALVIKVM_BOOT_OPT="-Ximage:${BOOT_IMAGE}"
-    else
-      DALVIKVM_BOOT_OPT="-Ximage:/system/non-existent/boot.art"
+    if [ "${RELOCATE}" = "n" ] ; then
+      BOOT_IMAGE="/system/non-existent/boot.art"
     fi
-else
-    DALVIKVM_BOOT_OPT="-Ximage:${BOOT_IMAGE}"
+    # App images cannot be generated without a boot image.
+    APP_IMAGE="n"
 fi
+DALVIKVM_BOOT_OPT="-Ximage:${BOOT_IMAGE}"
 
+if [ "$USE_GDB_DEX2OAT" = "y" ]; then
+  if [ "$HOST" = "n" ]; then
+    echo "The --gdb-dex2oat option is not yet implemented for target." >&2
+    exit 1
+  fi
+fi
 
 if [ "$USE_GDB" = "y" ]; then
   if [ "$USE_GDBSERVER" = "y" ]; then
-    echo "Cannot pass both --gdb and --gdbserver at the same time!" >&2
+    error_msg "Cannot pass both --gdb and --gdbserver at the same time!"
     exit 1
   elif [ "$HOST" = "n" ]; then
     # We might not have any hostname resolution if we are using a chroot.
@@ -813,7 +839,7 @@ if [ "$BIONIC" = "y" ]; then
   # This is the location that soong drops linux_bionic builds. Despite being
   # called linux_bionic-x86 the build is actually amd64 (x86_64) only.
   if [ ! -e "$OUT_DIR/soong/host/linux_bionic-x86" ]; then
-    echo "linux_bionic-x86 target doesn't seem to have been built!" >&2
+    error_msg "linux_bionic-x86 target doesn't seem to have been built!"
     exit 1
   fi
   # Set TIMEOUT_DUMPER manually so it works even with apex's
@@ -836,7 +862,7 @@ DEX_LOCATION_STRIPPED="${DEX_LOCATION#/}"
 VDEX_NAME="${DEX_LOCATION_STRIPPED//\//@}@$TEST_NAME.jar@classes.vdex"
 if [ ${#VDEX_NAME} -gt $max_filename_size ]; then
     echo "Dex location path too long:"
-    echo "$VDEX_NAME is ${#VDEX_NAME} character long, and the limit is $max_filename_size."
+    error_msg "$VDEX_NAME is ${#VDEX_NAME} character long, and the limit is $max_filename_size."
     exit 1
 fi
 
@@ -870,6 +896,8 @@ installapex_test_cmdline="true"
 
 linkdirs() {
   find "$1" -maxdepth 1 -mindepth 1 -type d | xargs -i ln -sf '{}' "$2"
+  # Also create a link for the boot image.
+  ln -sf $ANDROID_HOST_OUT/apex/art_boot_images "$2"
 }
 
 if [ "$CREATE_ANDROID_ROOT" = "y" ]; then
@@ -879,6 +907,8 @@ if [ "$CREATE_ANDROID_ROOT" = "y" ]; then
     # TODO Make this overlay more generic.
     linkroot_overlay_cmdline="linkdirs $OUT_DIR/soong/host/linux_bionic-x86 ${ANDROID_ROOT}"
   fi
+  # Replace the boot image to a location expected by the runtime.
+  DALVIKVM_BOOT_OPT="-Ximage:${ANDROID_ROOT}/art_boot_images/javalib/boot.art"
 fi
 
 if [ "$USE_ZIPAPEX" = "y" ]; then
@@ -927,6 +957,47 @@ if [ "$PROFILE" = "y" ] || [ "$RANDOM_PROFILE" = "y" ]; then
   fi
 fi
 
+function get_prebuilt_lldb_path {
+  local CLANG_BASE="prebuilts/clang/host"
+  local CLANG_VERSION="$("$ANDROID_BUILD_TOP/build/soong/scripts/get_clang_version.py")"
+  case "$(uname -s)" in
+    Darwin)
+      local PREBUILT_NAME="darwin-x86"
+      ;;
+    Linux)
+      local PREBUILT_NAME="linux-x86"
+      ;;
+    *)
+      >&2 echo "Unknown host $(uname -s). Unsupported for debugging dex2oat with LLDB."
+      return
+      ;;
+  esac
+  local CLANG_PREBUILT_HOST_PATH="$ANDROID_BUILD_TOP/$CLANG_BASE/$PREBUILT_NAME/$CLANG_VERSION"
+  # If the clang prebuilt directory exists and the reported clang version
+  # string does not, then it is likely that the clang version reported by the
+  # get_clang_version.py script does not match the expected directory name.
+  if [ -d "${ANDROID_BUILD_TOP}/${CLANG_BASE}/${PREBUILT_NAME}" ] && \
+     [ ! -d "${CLANG_PREBUILT_HOST_PATH}" ]; then
+    error_msg "The prebuilt clang directory exists, but the specific clang"\
+    "\nversion reported by get_clang_version.py does not exist in that path."\
+    "\nPlease make sure that the reported clang version resides in the"\
+    "\nprebuilt clang directory!"
+    exit 1
+  fi
+
+  # The lldb-server binary is a dependency of lldb.
+  export LLDB_DEBUGSERVER_PATH="${CLANG_PREBUILT_HOST_PATH}/runtimes_ndk_cxx/x86_64/lldb-server"
+
+  # Set the current terminfo directory to TERMINFO so that LLDB can read the
+  # termcap database.
+  local terminfo_regexp_path='\/.*\/*terminfo\/'
+  if [[ $(infocmp) =~ $terminfo_regexp_path ]] ; then
+    export TERMINFO="${BASH_REMATCH[0]}"
+  fi
+
+  prebuilt_lldb_path="$CLANG_PREBUILT_HOST_PATH/bin/lldb.sh"
+}
+
 function write_dex2oat_cmdlines {
   local name="$1"
 
@@ -939,7 +1010,17 @@ function write_dex2oat_cmdlines {
   # If the name ends in -ex then this is a secondary dex file
   if [ "${name:${#name}-3}" = "-ex" ]; then
     # Lazily realize the default value in case DEX_LOCATION/TEST_NAME change
-    [ -z "$SECONDARY_CLASS_LOADER_CONTEXT" ] && SECONDARY_CLASS_LOADER_CONTEXT="PCL[];PCL[$DEX_LOCATION/$TEST_NAME.jar]"
+    if [ "x$SECONDARY_CLASS_LOADER_CONTEXT" = "x" ]; then
+      if [ "x$SECONDARY_DEX" = "x" ]; then
+        # Tests without `--secondary` load the "-ex" jar in a separate PathClassLoader
+        # that is a child of the main PathClassLoader. If the class loader is constructed
+        # in any other way, the test needs to specify the secondary CLC explicitly.
+        SECONDARY_CLASS_LOADER_CONTEXT="PCL[];PCL[$DEX_LOCATION/$TEST_NAME.jar]"
+      else
+        # Tests with `--secondary` load the `-ex` jar a part of the main PathClassLoader.
+        SECONDARY_CLASS_LOADER_CONTEXT="PCL[$DEX_LOCATION/$TEST_NAME.jar]"
+      fi
+    fi
     class_loader_context="'--class-loader-context=$SECONDARY_CLASS_LOADER_CONTEXT'"
     $enable_app_image && [ "$SECONDARY_APP_IMAGE" = "y" ] || enable_app_image=false
   fi
@@ -947,12 +1028,20 @@ function write_dex2oat_cmdlines {
   local app_image=""
   $enable_app_image && app_image="--app-image-file=$DEX_LOCATION/oat/$ISA/$name.art --resolve-startup-const-strings=true"
 
+  if [ "$USE_GDB_DEX2OAT" = "y" ]; then
+    get_prebuilt_lldb_path
+    GDB_DEX2OAT="$prebuilt_lldb_path -f"
+    GDB_DEX2OAT_ARGS+=" -- "
+  fi
+
   local dex2oat_binary
   dex2oat_binary=${DEX2OAT_DEBUG_BINARY}
   if  [[ "$TEST_IS_NDEBUG" = "y" ]]; then
     dex2oat_binary=${DEX2OAT_NDEBUG_BINARY}
   fi
-  dex2oat_cmdline="$INVOKE_WITH $ANDROID_ART_BIN_DIR/$dex2oat_binary \
+  dex2oat_cmdline="$INVOKE_WITH $GDB_DEX2OAT \
+                      $ANDROID_ART_BIN_DIR/$dex2oat_binary \
+                      $GDB_DEX2OAT_ARGS \
                       $COMPILE_FLAGS \
                       --boot-image=${BOOT_IMAGE} \
                       --dex-file=$DEX_LOCATION/$name.jar \
@@ -966,12 +1055,13 @@ function write_dex2oat_cmdlines {
   fi
 
   # Add in a timeout. This is important for testing the compilation/verification time of
-  # pathological cases.
+  # pathological cases. We do not append a timeout when debugging dex2oat because we
+  # do not want it to exit while debugging.
   # Note: as we don't know how decent targets are (e.g., emulator), only do this on the host for
   #       now. We should try to improve this.
   #       The current value is rather arbitrary. run-tests should compile quickly.
   # Watchdog timeout is in milliseconds so add 3 '0's to the dex2oat timeout.
-  if [ "$HOST" != "n" ]; then
+  if [ "$HOST" != "n" ] && [ "$USE_GDB_DEX2OAT" != "y" ]; then
     # Use SIGRTMIN+2 to try to dump threads.
     # Use -k 1m to SIGKILL it a minute later if it hasn't ended.
     dex2oat_cmdline="timeout -k ${DEX2OAT_TIMEOUT}s -s SIGRTMIN+2 ${DEX2OAT_RT_TIMEOUT}s ${dex2oat_cmdline} --watchdog-timeout=${DEX2OAT_TIMEOUT}000"
@@ -985,10 +1075,13 @@ function write_dex2oat_cmdlines {
     else
       vdex_cmdline="${dex2oat_cmdline} ${VDEX_ARGS} --input-vdex=$DEX_LOCATION/oat/$ISA/$name.vdex"
     fi
-  elif [ "$TEST_DM" = "y" ]; then
+  elif [ "$TEST_DEX2OAT_DM" = "y" ]; then
+    vdex_cmdline="${dex2oat_cmdline} ${VDEX_ARGS} --dump-timings --dm-file=$DEX_LOCATION/oat/$ISA/$name.dm"
     dex2oat_cmdline="${dex2oat_cmdline} --copy-dex-files=false --output-vdex=$DEX_LOCATION/oat/$ISA/primary.vdex"
     dm_cmdline="zip -qj $DEX_LOCATION/oat/$ISA/$name.dm $DEX_LOCATION/oat/$ISA/primary.vdex"
-    vdex_cmdline="${dex2oat_cmdline} ${VDEX_ARGS} --dump-timings --dm-file=$DEX_LOCATION/oat/$ISA/$name.dm"
+  elif [ "$TEST_RUNTIME_DM" = "y" ]; then
+    dex2oat_cmdline="${dex2oat_cmdline} --copy-dex-files=false --output-vdex=$DEX_LOCATION/oat/$ISA/primary.vdex"
+    dm_cmdline="zip -qj $DEX_LOCATION/$name.dm $DEX_LOCATION/oat/$ISA/primary.vdex"
   fi
 }
 
@@ -1049,9 +1142,16 @@ else
   QUOTED_DALVIKVM_BOOT_OPT="$DALVIKVM_BOOT_OPT"
 fi
 
+DALVIKVM_CLASSPATH=$DEX_LOCATION/$TEST_NAME.jar
+if [ -f "$TEST_NAME-aotex.jar" ] ; then
+  DALVIKVM_CLASSPATH=$DALVIKVM_CLASSPATH:$DEX_LOCATION/$TEST_NAME-aotex.jar
+fi
+DALVIKVM_CLASSPATH=$DALVIKVM_CLASSPATH$SECONDARY_DEX
+
 # We set DumpNativeStackOnSigQuit to false to avoid stressing libunwind.
 # b/27185632
 # b/24664297
+
 dalvikvm_cmdline="$INVOKE_WITH $GDB $ANDROID_ART_BIN_DIR/$DALVIKVM \
                   $GDB_ARGS \
                   $FLAGS \
@@ -1066,7 +1166,11 @@ dalvikvm_cmdline="$INVOKE_WITH $GDB $ANDROID_ART_BIN_DIR/$DALVIKVM \
                   ${QUOTED_DALVIKVM_BOOT_OPT} \
                   $TMP_DIR_OPTION \
                   -XX:DumpNativeStackOnSigQuit:false \
-                  -cp $DEX_LOCATION/$TEST_NAME.jar$SECONDARY_DEX $MAIN $ARGS"
+                  -cp $DALVIKVM_CLASSPATH $MAIN $ARGS"
+
+if [ "x$SIMPLEPERF" == xyes ]; then
+  dalvikvm_cmdline="simpleperf record ${dalvikvm_cmdline} && simpleperf report"
+fi
 
 sanitize_dex2oat_cmdline() {
   local args=()
@@ -1119,6 +1223,8 @@ if [ "$HOST" = "n" ]; then
       adb shell mkdir -p $CHROOT_DEX_LOCATION
       adb push $TEST_NAME.jar $CHROOT_DEX_LOCATION
       adb push $TEST_NAME-ex.jar $CHROOT_DEX_LOCATION
+      adb push $TEST_NAME-aotex.jar $CHROOT_DEX_LOCATION
+      adb push $TEST_NAME-bcpex.jar $CHROOT_DEX_LOCATION
       if [ "$PROFILE" = "y" ] || [ "$RANDOM_PROFILE" = "y" ]; then
         adb push profile $CHROOT_DEX_LOCATION
       fi
@@ -1131,6 +1237,8 @@ if [ "$HOST" = "n" ]; then
       adb shell mkdir -p $CHROOT_DEX_LOCATION >/dev/null 2>&1
       adb push $TEST_NAME.jar $CHROOT_DEX_LOCATION >/dev/null 2>&1
       adb push $TEST_NAME-ex.jar $CHROOT_DEX_LOCATION >/dev/null 2>&1
+      adb push $TEST_NAME-aotex.jar $CHROOT_DEX_LOCATION >/dev/null 2>&1
+      adb push $TEST_NAME-bcpex.jar $CHROOT_DEX_LOCATION >/dev/null 2>&1
       if [ "$PROFILE" = "y" ] || [ "$RANDOM_PROFILE" = "y" ]; then
         adb push profile $CHROOT_DEX_LOCATION >/dev/null 2>&1
       fi
diff --git a/art/test/run-test b/art/test/run-test
--- a/art/test/run-test
+++ b/art/test/run-test
@@ -44,32 +44,6 @@ export JAVA="java"
 export JAVAC="javac -g -Xlint:-options -source 1.8 -target 1.8"
 export RUN="${progdir}/etc/run-test-jar"
 export DEX_LOCATION=/data/run-test/${test_dir}
-export NEED_DEX="true"
-export USE_D8="true"
-export USE_DESUGAR="true"
-export SMALI_ARGS=""
-
-# If d8 was not set by the environment variable, assume it is in the path.
-if [ -z "$D8" ]; then
-  export D8="d8"
-fi
-
-# If dx was not set by the environment variable, assume it is in the path.
-if [ -z "$DX" ]; then
-  export DX="d8-compat-dx"
-fi
-
-export DEXMERGER="$D8"
-
-# If jasmin was not set by the environment variable, assume it is in the path.
-if [ -z "$JASMIN" ]; then
-  export JASMIN="jasmin"
-fi
-
-# If smali was not set by the environment variable, assume it is in the path.
-if [ -z "$SMALI" ]; then
-  export SMALI="smali"
-fi
 
 # ANDROID_BUILD_TOP is not set in a build environment.
 if [ -z "$ANDROID_BUILD_TOP" ]; then
@@ -89,52 +63,19 @@ if [ -z "$ANDROID_HOST_OUT" ]; then
 fi
 
 host_lib_root=${ANDROID_HOST_OUT}
-
-# Allow changing DESUGAR script to something else, or to disable it with DESUGAR=false.
-if [ -z "$DESUGAR" ]; then
-  export DESUGAR="$ANDROID_BUILD_TOP/art/tools/desugar.sh"
-fi
-
-# Zipalign is not on the PATH in some configs, auto-detect it.
-if [ -z "$ZIPALIGN" ]; then
-  if which zipalign >/dev/null; then
-    ZIPALIGN="zipalign";
-  else
-    # TODO: Add a dependency for zipalign in Android.run-test.mk
-    # once it doesn't depend on libandroidfw (b/35246701)
-    case "$OSTYPE" in
-      darwin*)  ZIPALIGN="$ANDROID_BUILD_TOP/prebuilts/sdk/tools/darwin/bin/zipalign" ;;
-      linux*)   ZIPALIGN="$ANDROID_BUILD_TOP/prebuilts/sdk/tools/linux/bin/zipalign" ;;
-      *)        echo "Can't find zipalign: unknown: $OSTYPE" >&2;;
-    esac
-  fi
-fi
-export ZIPALIGN
-
-# If hiddenapi was not set by the environment variable, assume it is in
-# ANDROID_HOST_OUT.
-if [ -z "$HIDDENAPI" ]; then
-  export HIDDENAPI="${ANDROID_HOST_OUT}/bin/hiddenapi"
-fi
-
 chroot=
-
 info="info.txt"
-build="build"
 run="run"
 expected_stdout="expected-stdout.txt"
 expected_stderr="expected-stderr.txt"
 check_cmd="check"
 test_stdout="test-stdout.txt"
 test_stderr="test-stderr.txt"
-build_stdout="build-stdout.txt"
-build_stderr="build-stderr.txt"
 cfg_output="graph.cfg"
 strace_output="strace-output.txt"
 lib="libartd.so"
 testlib="arttestd"
 run_args=(--quiet)
-build_args=""
 
 quiet="no"
 debuggable="no"
@@ -147,7 +88,6 @@ debug_mode="no"
 relocate="no"
 runtime="art"
 usage="no"
-build_only="no"
 suffix64=""
 trace="false"
 trace_stream="false"
@@ -167,7 +107,8 @@ bisection_search="no"
 timeout=""
 suspend_timeout="500000"
 run_optimizing="false"
-
+dump_cfg="false"
+dump_cfg_path=""
 # To cause tests to fail fast, limit the file sizes created by dx, dex2oat and
 # ART output to approximately 128MB. This should be more than sufficient
 # for any test while still catching cases of runaway output.
@@ -201,7 +142,6 @@ while true; do
         DEX_LOCATION="$tmp_dir"
         runtime="jvm"
         prebuild_mode="no"
-        NEED_DEX="false"
         run_args+=(--jvm)
         shift
     elif [ "x$1" = "x-O" ]; then
@@ -276,11 +216,6 @@ while true; do
         option="$1"
         run_args+=(-Xcompiler-option "$option")
         shift
-    elif [ "x$1" = "x--build-option" ]; then
-        shift
-        option="$1"
-        build_args="${build_args} $option"
-        shift
     elif [ "x$1" = "x--runtime-option" ]; then
         shift
         option="$1"
@@ -290,6 +225,11 @@ while true; do
         shift
         gdb_arg="$1"
         run_args+=(--gdb-arg "$gdb_arg")
+        shift
+    elif [ "x$1" = "x--gdb-dex2oat-args" ]; then
+        shift
+        gdb_dex2oat_args="$1"
+        run_args+=(--gdb-dex2oat-args "$gdb_dex2oat_args")
         shift
     elif [ "x$1" = "x--debug" ]; then
         run_args+=(--debug)
@@ -307,8 +247,17 @@ while true; do
         option="$1"
         run_args+=(--debug-agent "$1")
         shift
+    elif [ "x$1" = "x--dump-cfg" ]; then
+        shift
+        dump_cfg="true"
+        dump_cfg_path="$1"
+        shift
     elif [ "x$1" = "x--gdb" ]; then
         run_args+=(--gdb)
+        dev_mode="yes"
+        shift
+    elif [ "x$1" = "x--gdb-dex2oat" ]; then
+        run_args+=(--gdb-dex2oat)
         dev_mode="yes"
         shift
     elif [ "x$1" = "x--gdbserver-bin" ]; then
@@ -378,14 +327,11 @@ while true; do
         run_args+=(--dev)
         dev_mode="yes"
         shift
-    elif [ "x$1" = "x--build-only" ]; then
-        build_only="yes"
-        shift
-    elif [ "x$1" = "x--output-path" ]; then
+    elif [ "x$1" = "x--temp-path" ]; then
         shift
         tmp_dir=$1
         if [ "x$tmp_dir" = "x" ]; then
-            echo "$0 missing argument to --output-path" 1>&2
+            echo "$0 missing argument to --temp-path" 1>&2
             usage="yes"
             break
         fi
@@ -399,6 +345,9 @@ while true; do
         fi
         chroot="$1"
         run_args+=(--chroot "$1")
+        shift
+    elif [ "x$1" = "x--simpleperf" ]; then
+        run_args+=(--simpleperf)
         shift
     elif [ "x$1" = "x--android-root" ]; then
         shift
@@ -621,8 +570,8 @@ fi
 function guess_target_arch_name() {
     # Check whether this is a device with native bridge. Currently this is hardcoded
     # to x86 + arm.
-    local guess_path=${ANDROID_PRODUCT_OUT}/system/apex/com.android.art.testing/javalib
-    local x86_arm=`ls ${guess_path} | sort | grep -E '^(arm|x86)$'`
+    local guess_path=$chroot/system/framework/art_boot_images
+    local x86_arm=`adb shell ls ${guess_path} | sort | grep -E '^(arm|x86)$'`
     # Collapse line-breaks into spaces
     x86_arm=$(echo $x86_arm)
     if [ "x$x86_arm" = "xarm x86" ] ; then
@@ -634,8 +583,8 @@ function guess_target_arch_name() {
             target_arch_name=x86
         fi
     else
-        local grep32bit=`ls ${guess_path} | grep -E '^(arm|x86)$'`
-        local grep64bit=`ls ${guess_path} | grep -E '^(arm64|x86_64)$'`
+        local grep32bit=`adb shell ls ${guess_path} | grep -E '^(arm|x86)$'`
+        local grep64bit=`adb shell ls ${guess_path} | grep -E '^(arm64|x86_64)$'`
         if [ "x${suffix64}" = "x64" ]; then
             target_arch_name=${grep64bit}
         else
@@ -691,7 +640,7 @@ elif [ "$runtime" = "art" ]; then
         # need to be loaded through LD_LIBRARY_PATH and
         # NATIVELOADER_DEFAULT_NAMESPACE_LIBS instead.
         run_args+=(--runtime-option "-Djava.library.path=/data/nativetest${suffix64}/art/${target_arch_name}")
-        run_args+=(--boot "/apex/com.android.art/javalib/boot.art")
+        run_args+=(--boot "/system/framework/art_boot_images/boot.art")
     fi
     if [ "$relocate" = "yes" ]; then
       run_args+=(--relocate)
@@ -777,7 +726,6 @@ if [ "$usage" = "yes" ]; then
         echo "  Runtime Options:"
         echo "    -O                    Run non-debug rather than debug build (off by default)."
         echo "    -Xcompiler-option     Pass an option to the compiler."
-        echo "    --build-option        Pass an option to the build script."
         echo "    --runtime-option      Pass an option to the runtime."
         echo "    --compact-dex-level   Specify a compact dex level to the compiler."
         echo "    --debug               Wait for the default debugger to attach."
@@ -789,13 +737,17 @@ if [ "$usage" = "yes" ]; then
         echo "    --with-agent <agent>  Run the test with the given agent loaded with -agentpath:"
         echo "    --debuggable          Whether to compile Java code for a debugger."
         echo "    --gdb                 Run under gdb; incompatible with some tests."
+        echo "    --gdb-dex2oat         Run dex2oat under the prebuilt lldb."
         echo "    --gdbserver           Start gdbserver (defaults to port :5039)."
         echo "    --gdbserver-port <port>"
         echo "                          Start gdbserver with the given COMM (see man gdbserver)."
         echo "    --gdbserver-bin <binary>"
         echo "                          Use the given binary as gdbserver."
         echo "    --gdb-arg             Pass an option to gdb or gdbserver."
-        echo "    --build-only          Build test files only (off by default)."
+        echo "    --gdb-dex2oat-args    Pass options separated by ';' to lldb for dex2oat."
+        echo "    --simpleperf          Wraps the dalvikvm invocation in 'simpleperf record ..."
+        echo "                          ... simpleperf report' and dumps stats to stdout."
+        echo "    --temp-path [path]    Location where to execute the tests."
         echo "    --interpreter         Enable interpreter only mode (off by default)."
         echo "    --jit                 Enable jit (off by default)."
         echo "    --optimizing          Enable optimizing compiler (default)."
@@ -825,8 +777,6 @@ if [ "$usage" = "yes" ]; then
         echo "    --use-java-home       Use the JAVA_HOME environment variable"
         echo "                          to find the java compiler and runtime"
         echo "                          (if applicable) to run the test with."
-        echo "    --output-path [path]  Location where to store the build" \
-             "files."
         echo "    --64                  Run the test in 64-bit mode"
         echo "    --bionic              Use the (host, 64-bit only) linux_bionic libc runtime"
         echo "    --runtime-zipapex [file]"
@@ -885,44 +835,16 @@ for td_file in "$td_info" "$td_expected_stdout" "$td_expected_stderr"; do
     fi
 done
 
-# copy the test to a temp dir and run it
-
-echo "${test_dir}: building..." 1>&2
-
-rm -rf "$tmp_dir"
-cp -LRp "$test_dir" "$tmp_dir"
-cd "$tmp_dir"
-
-if [ '!' -r "$build" ]; then
-    cp "${progdir}/etc/default-build" build
-else
-    cp "${progdir}/etc/default-build" .
-fi
-
-if [ '!' -r "$run" ]; then
-    cp "${progdir}/etc/default-run" run
-else
-    cp "${progdir}/etc/default-run" .
-fi
-
-if [ '!' -r "$check_cmd" ]; then
-    cp "${progdir}/etc/default-check" check
-else
-    cp "${progdir}/etc/default-check" .
-fi
-
-chmod 755 "$build"
-chmod 755 "$run"
-chmod 755 "$check_cmd"
-
 export TEST_NAME=`basename ${test_dir}`
 
 # Tests named '<number>-checker-*' will also have their CFGs verified with
 # Checker when compiled with Optimizing on host.
-if [[ "$TEST_NAME" =~ ^[0-9]+-checker- ]]; then
+# Additionally, if the user specifies that the CFG must be dumped, it will
+# run the checker for any type of test to generate the CFG.
+if [[ "$TEST_NAME" =~ ^[0-9]+-checker- ]] || [ "$dump_cfg" = "true" ]; then
   if [ "$runtime" = "art" -a "$run_optimizing" = "true" ]; then
     # In no-prebuild or no-image mode, the compiler only quickens so disable the checker.
-    if [ "$prebuild_mode" = "yes" -a "$have_image" = "yes" ]; then
+    if [ "$prebuild_mode" = "yes" ]; then
       run_checker="yes"
 
       if [ "$target_mode" = "no" ]; then
@@ -949,144 +871,84 @@ if ! ulimit -f ${file_ulimit}; then
   err_echo "ulimit file size setting failed"
 fi
 
-# Tell the build script which mode (target, host, jvm) we are building for
-# to determine the bootclasspath at build time.
+# Extract run-test data from the zip file.
+rm -rf "$tmp_dir"
+mkdir -p "$tmp_dir/.unzipped"
+cd "$tmp_dir"
 if [[ "$target_mode" == "yes" ]]; then
-  build_args="$build_args --target"
+  zip_file="${ANDROID_HOST_OUT}/etc/art/art-run-test-target-data.zip"
+  zip_entry="target/${TEST_NAME}"
+elif [[ $runtime == "jvm" ]]; then
+  zip_file="${ANDROID_HOST_OUT}/etc/art/art-run-test-jvm-data.zip"
+  zip_entry="jvm/${TEST_NAME}"
 else
-  if [[ $runtime == "jvm" ]]; then
-    build_args="$build_args --jvm"
-  else
-    build_args="$build_args --host"
-  fi
+  zip_file="${ANDROID_HOST_OUT}/etc/art/art-run-test-host-data.zip"
+  zip_entry="host/${TEST_NAME}"
 fi
-
-if [[ "$dev_mode" == "yes" ]]; then
-  build_args="$build_args --dev"
-fi
+unzip -q "${zip_file}" "${zip_entry}/*" -d "$tmp_dir/.unzipped"
+mv "$tmp_dir"/.unzipped/${zip_entry}/* "$tmp_dir"
 
 good="no"
-good_build="yes"
 good_run="yes"
 export TEST_RUNTIME="${runtime}"
 if [ "$dev_mode" = "yes" ]; then
-    "./${build}" $build_args
-    build_exit="$?"
-    echo "build exit status: $build_exit" 1>&2
-    if [ "$build_exit" = '0' ]; then
-        echo "${test_dir}: running..." 1>&2
-        "./${run}" "${run_args[@]}" "$@"
-        run_exit="$?"
+    echo "${test_dir}: running..." 1>&2
+    "./${run}" "${run_args[@]}" "$@"
+    run_exit="$?"
 
-        if [ "$run_exit" = "0" ]; then
-            if [ "$run_checker" = "yes" ]; then
-                if [ "$target_mode" = "yes" ]; then
-                  adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
-                fi
-                "$checker" $checker_args "$cfg_output" "$tmp_dir" 2>&1
-                checker_exit="$?"
-                if [ "$checker_exit" = "0" ]; then
-                    good="yes"
-                fi
-                err_echo "checker exit status: $checker_exit"
-            else
-                good="yes"
-            fi
-        fi
-        echo "run exit status: $run_exit" 1>&2
-    fi
-elif [ "$update_mode" = "yes" ]; then
-    "./${build}" $build_args >"$build_stdout" 2>"$build_stderr"
-    build_exit="$?"
-    if [ "$build_exit" = '0' ]; then
-        echo "${test_dir}: running..." 1>&2
-        "./${run}" "${run_args[@]}" "$@" >"$test_stdout" 2>"$test_stderr"
+    if [ "$run_exit" = "0" ]; then
         if [ "$run_checker" = "yes" ]; then
-          if [ "$target_mode" = "yes" ]; then
-            adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
-          fi
-          "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >>"$test_stdout" 2>>"$test_stderr"
-        fi
-        sed -e 's/[[:cntrl:]]$//g' <"$test_stdout" >"${td_expected_stdout}"
-        sed -e 's/[[:cntrl:]]$//g' <"$test_stderr" >"${td_expected_stderr}"
-        good="yes"
-    else
-        err_echo "#################### build standard output"
-        cat "$build_stdout" 1>&${real_stderr}
-        err_echo "####################"
-        err_echo "#################### build standard error"
-        cat "$build_stderr" 1>&${real_stderr}
-        err_echo "####################"
-        err_echo "build exit status: $build_exit"
-    fi
-elif [ "$build_only" = "yes" ]; then
-    good="yes"
-    "./${build}" $build_args >"$build_stdout" 2>"$build_stderr"
-    build_exit="$?"
-    if [ "$build_exit" '!=' '0' ]; then
-        cp "$build_stdout" "$test_stdout"
-        diff --strip-trailing-cr -q "$expected_stdout" "$test_stdout" >/dev/null
-        if [ "$?" '!=' "0" ]; then
-            good="no"
-            err_echo "BUILD FAILED For ${TEST_NAME}" \
-              "(the build's standard output does not match the expected standard output)"
-        fi
-        cp "$build_stderr" "$test_stderr"
-        diff --strip-trailing-cr -q "$expected_stderr" "$test_stderr" >/dev/null
-        if [ "$?" '!=' "0" ]; then
-            good="no"
-            err_echo "BUILD FAILED For ${TEST_NAME}" \
-              "(the build's standard error does not match the expected standard error)"
-        fi
-        echo "build exit status: $build_exit" >>"$test_stderr"
-    fi
-    # Clean up extraneous files that are not used by tests.
-    find $tmp_dir -mindepth 1  \
-        ! -regex ".*/\(.*jar\|$test_stdout\|$expected_stdout|$test_stderr\|$expected_stderr\)" \
-      | xargs rm -rf
-    exit 0
-else
-    "./${build}" $build_args >"$build_stdout" 2>"$build_stderr"
-    build_exit="$?"
-    if [ "$build_exit" = '0' ]; then
-        echo "${test_dir}: running..." 1>&2
-        "./${run}" "${run_args[@]}" "$@" >"$test_stdout" 2>"$test_stderr"
-        run_exit="$?"
-        if [ "$run_exit" != "0" ]; then
-            err_echo "run exit status: $run_exit"
-            good_run="no"
-        elif [ "$run_checker" = "yes" ]; then
             if [ "$target_mode" = "yes" ]; then
               adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
             fi
-            "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >>"$test_stdout" 2>>"$test_stderr"
+            "$checker" $checker_args "$cfg_output" "$tmp_dir" 2>&1
             checker_exit="$?"
-            if [ "$checker_exit" != "0" ]; then
-                err_echo "checker exit status: $checker_exit"
-                good_run="no"
-            else
-                good_run="yes"
+            if [ "$checker_exit" = "0" ]; then
+                good="yes"
             fi
+            err_echo "checker exit status: $checker_exit"
+        else
+            good="yes"
+        fi
+    fi
+    echo "run exit status: $run_exit" 1>&2
+elif [ "$update_mode" = "yes" ]; then
+    echo "${test_dir}: running..." 1>&2
+    "./${run}" "${run_args[@]}" "$@" >"$test_stdout" 2>"$test_stderr"
+    if [ "$run_checker" = "yes" ]; then
+      if [ "$target_mode" = "yes" ]; then
+        adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
+      fi
+      "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >>"$test_stdout" 2>>"$test_stderr"
+    fi
+    sed -e 's/[[:cntrl:]]$//g' <"$test_stdout" >"${td_expected_stdout}"
+    sed -e 's/[[:cntrl:]]$//g' <"$test_stderr" >"${td_expected_stderr}"
+    good="yes"
+else
+    echo "${test_dir}: running..." 1>&2
+    "./${run}" "${run_args[@]}" "$@" >"$test_stdout" 2>"$test_stderr"
+    run_exit="$?"
+    if [ "$run_exit" != "0" ]; then
+        err_echo "run exit status: $run_exit"
+        good_run="no"
+    elif [ "$run_checker" = "yes" ]; then
+        if [ "$target_mode" = "yes" ]; then
+          adb pull "$chroot/$cfg_output_dir/$cfg_output" &> /dev/null
+        fi
+        "$checker" -q $checker_args "$cfg_output" "$tmp_dir" >>"$test_stdout" 2>>"$test_stderr"
+        checker_exit="$?"
+        if [ "$checker_exit" != "0" ]; then
+            err_echo "checker exit status: $checker_exit"
+            good_run="no"
         else
             good_run="yes"
         fi
     else
-        good_build="no"
-        cp "$build_stdout" "$test_stdout"
-        cp "$build_stderr" "$test_stderr"
-        echo "Failed to build in tmpdir=${tmp_dir} from oldwd=${oldwd} and cwd=`pwd`" \
-          >> "$test_stderr"
-        echo "Non-canonical tmpdir was ${noncanonical_tmp_dir}" >> "$test_stderr"
-        echo "Args: ${args}" >> "$test_stderr"
-        echo "build exit status: $build_exit" >> "$test_stderr"
-        max_name_length=$(getconf NAME_MAX ${tmp_dir})
-        echo "Max filename (NAME_MAX): ${max_name_length}" >> "$test_stderr"
-        max_path_length=$(getconf PATH_MAX ${tmp_dir})
-        echo "Max pathlength (PATH_MAX): ${max_path_length}" >> "$test_stderr"
+        good_run="yes"
     fi
     ./$check_cmd "$expected_stdout" "$test_stdout" "$expected_stderr" "$test_stderr"
     if [ "$?" = "0" ]; then
-        if [ "$good_build" = "no" -o "$good_run" = "yes" ]; then
+        if [ "$good_run" = "yes" ]; then
           # test_stdout == expected_stdout && test_stderr == expected_stderr
           good="yes"
           echo "${test_dir}: succeeded!" 1>&2
@@ -1126,6 +988,19 @@ fi
     fi
 
 ) 2>&${real_stderr} 1>&2
+
+# Copy the generated CFG to the specified path.
+if [ $dump_cfg = "true" ]; then
+    if [ $run_optimizing != "true" ]; then
+        err_echo "Can't dump the .cfg if the compiler type isn't set to \"optimizing\"."
+    else
+        if [ "$target_mode" = "yes" ]; then
+            adb pull $chroot/$cfg_output_dir/$cfg_output $dump_cfg_path
+        else
+            cp $cfg_output_dir/$cfg_output $dump_cfg_path
+        fi
+    fi
+fi
 
 # Attempt bisection only if the test failed.
 # TODO: Implement support for chroot-based bisection search.
diff --git a/external/oss-fuzz/infra/base-images/base-runner/coverage b/external/oss-fuzz/infra/base-images/base-runner/coverage
--- a/external/oss-fuzz/infra/base-images/base-runner/coverage
+++ b/external/oss-fuzz/infra/base-images/base-runner/coverage
@@ -19,14 +19,21 @@ cd $OUT
 if (( $# > 0 )); then
   FUZZ_TARGETS="$@"
 else
-  FUZZ_TARGETS="$(find . -maxdepth 1 -type f -executable -printf '%P\n')"
+  FUZZ_TARGETS="$(find . -maxdepth 1 -type f -executable -printf '%P\n' | \
+      grep -v -x -F \
+      -e 'llvm-symbolizer' \
+      -e 'jazzer_agent_deploy.jar' \
+      -e 'jazzer_driver' \
+      -e 'jazzer_driver_with_sanitizer')"
 fi
 
-DUMPS_DIR="$OUT/dumps"
-FUZZER_STATS_DIR="$OUT/fuzzer_stats"
-LOGS_DIR="$OUT/logs"
-REPORT_ROOT_DIR="$OUT/report"
-REPORT_PLATFORM_DIR="$OUT/report/linux"
+COVERAGE_OUTPUT_DIR=${COVERAGE_OUTPUT_DIR:-$OUT}
+
+DUMPS_DIR="$COVERAGE_OUTPUT_DIR/dumps"
+FUZZER_STATS_DIR="$COVERAGE_OUTPUT_DIR/fuzzer_stats"
+LOGS_DIR="$COVERAGE_OUTPUT_DIR/logs"
+REPORT_ROOT_DIR="$COVERAGE_OUTPUT_DIR/report"
+REPORT_PLATFORM_DIR="$COVERAGE_OUTPUT_DIR/report/linux"
 
 for directory in $DUMPS_DIR $FUZZER_STATS_DIR $LOGS_DIR $REPORT_ROOT_DIR \
                  $REPORT_PLATFORM_DIR; do
@@ -54,6 +61,8 @@ objects=""
 # Number of CPUs available, this is needed for running tests in parallel.
 NPROC=$(nproc)
 
+CORPUS_DIR=${CORPUS_DIR:-"/corpus"}
+
 function run_fuzz_target {
   local target=$1
 
@@ -62,7 +71,7 @@ function run_fuzz_target {
   local profraw_file="$DUMPS_DIR/$target.%1m.profraw"
   local profraw_file_mask="$DUMPS_DIR/$target.*.profraw"
   local profdata_file="$DUMPS_DIR/$target.profdata"
-  local corpus_real="/corpus/${target}"
+  local corpus_real="$CORPUS_DIR/${target}"
 
   # -merge=1 requires an output directory, create a new, empty dir for that.
   local corpus_dummy="$OUT/dummy_corpus_dir_for_${target}"
@@ -74,7 +83,7 @@ function run_fuzz_target {
   # because (A) corpuses are already minimized; (B) we do not use sancov, and so
   # libFuzzer always finishes merge with an empty output dir.
   # Use 100s timeout instead of 25s as code coverage builds can be very slow.
-  local args="-merge=1 -timeout=100 -close_fd_mask=3 $corpus_dummy $corpus_real"
+  local args="-merge=1 -timeout=100 $corpus_dummy $corpus_real"
 
   export LLVM_PROFILE_FILE=$profraw_file
   timeout $TIMEOUT $OUT/$target $args &> $LOGS_DIR/$target.log
@@ -90,6 +99,9 @@ function run_fuzz_target {
     return 0
   fi
 
+  # If necessary translate to latest profraw version.
+  profraw_update.py $OUT/$target $profraw_file_mask tmp.profraw
+  mv tmp.profraw $profraw_file_mask
   llvm-profdata merge -j=1 -sparse $profraw_file_mask -o $profdata_file
 
   # Delete unnecessary and (potentially) large .profraw files.
@@ -115,7 +127,7 @@ function run_go_fuzz_target {
   local target=$1
 
   echo "Running go target $target"
-  export FUZZ_CORPUS_DIR="/corpus/${target}/"
+  export FUZZ_CORPUS_DIR="$CORPUS_DIR/${target}/"
   export FUZZ_PROFILE_NAME="$DUMPS_DIR/$target.perf"
   $OUT/$target -test.coverprofile $DUMPS_DIR/$target.profdata &> $LOGS_DIR/$target.log
   # translate from golangish paths to current absolute paths
@@ -123,6 +135,47 @@ function run_go_fuzz_target {
   # cf PATH_EQUIVALENCE_ARGS
   sed -i 's=/='$OUT'/=' $DUMPS_DIR/$target.profdata
   $SYSGOPATH/bin/gocovsum $DUMPS_DIR/$target.profdata > $FUZZER_STATS_DIR/$target.json
+}
+
+function run_java_fuzz_target {
+  local target=$1
+
+  local exec_file="$DUMPS_DIR/$target.exec"
+  local class_dump_dir="$DUMPS_DIR/${target}_classes/"
+  mkdir "$class_dump_dir"
+  local corpus_real="$CORPUS_DIR/${target}"
+
+  # -merge=1 requires an output directory, create a new, empty dir for that.
+  local corpus_dummy="$OUT/dummy_corpus_dir_for_${target}"
+  rm -rf $corpus_dummy && mkdir -p $corpus_dummy
+
+  # Use 100s timeout instead of 25s as code coverage builds can be very slow.
+  local jacoco_args="destfile=$exec_file,classdumpdir=$class_dump_dir,excludes=com.code_intelligence.jazzer.*"
+  local args="-merge=1 -timeout=100 --nohooks \
+      --additional_jvm_args=-javaagent:/opt/jacoco-agent.jar=$jacoco_args \
+      $corpus_dummy $corpus_real"
+
+  timeout $TIMEOUT $OUT/$target $args &> $LOGS_DIR/$target.log
+  if (( $? != 0 )); then
+    echo "Error occured while running $target:"
+    cat $LOGS_DIR/$target.log
+  fi
+
+  if (( $(du -c $exec_file | tail -n 1 | cut -f 1) == 0 )); then
+    # Skip fuzz targets that failed to produce .exec files.
+    return 0
+  fi
+
+  # Generate XML report only as input to jacoco_report_converter.
+  # Source files are not needed for the summary.
+  local xml_report="$DUMPS_DIR/${target}.xml"
+  local summary_file="$FUZZER_STATS_DIR/$target.json"
+  java -jar /opt/jacoco-cli.jar report $exec_file \
+      --xml $xml_report \
+      --classfiles $class_dump_dir
+
+  # Write llvm-cov summary file.
+  jacoco_report_converter.py $xml_report $summary_file
 }
 
 export SYSGOPATH=$GOPATH
@@ -136,6 +189,14 @@ for fuzz_target in $FUZZ_TARGETS; do
       grep "FUZZ_CORPUS_DIR" $fuzz_target > /dev/null 2>&1 || continue
     fi
     run_go_fuzz_target $fuzz_target &
+  elif [[ $FUZZING_LANGUAGE == "jvm" ]]; then
+    # Continue if not a fuzz target.
+    if [[ $FUZZING_ENGINE != "none" ]]; then
+      grep "LLVMFuzzerTestOneInput" $fuzz_target > /dev/null 2>&1 || continue
+    fi
+
+    echo "Running $fuzz_target"
+    run_java_fuzz_target $fuzz_target &
   else
     # Continue if not a fuzz target.
     if [[ $FUZZING_ENGINE != "none" ]]; then
@@ -175,6 +236,43 @@ if [[ $FUZZING_LANGUAGE == "go" ]]; then
   mv merged.data $REPORT_ROOT_DIR/heap.prof
   #TODO some proxy for go tool pprof -http=127.0.0.1:8001 $DUMPS_DIR/cpu.prof
   echo "Finished generating code coverage report for Go fuzz targets."
+elif [[ $FUZZING_LANGUAGE == "jvm" ]]; then
+
+  # From this point on the script does not tolerate any errors.
+  set -e
+
+  # Merge .exec files from the individual targets.
+  jacoco_merged_exec=$DUMPS_DIR/jacoco.merged.exec
+  java -jar /opt/jacoco-cli.jar merge $DUMPS_DIR/*.exec \
+      --destfile $jacoco_merged_exec
+
+  # Merge .class files from the individual targets.
+  classes_dir=$DUMPS_DIR/classes
+  mkdir $classes_dir
+  for fuzz_target in $FUZZ_TARGETS; do
+    cp -r $DUMPS_DIR/${fuzz_target}_classes/* $classes_dir/
+  done
+
+  # Heuristically determine source directories based on Maven structure.
+  # Always include the $SRC root as it likely contains the fuzzer sources.
+  sourcefiles_args=(--sourcefiles $OUT/$SRC)
+  source_dirs=$(find $OUT/$SRC -type d -name 'java')
+  for source_dir in $source_dirs; do
+    sourcefiles_args+=(--sourcefiles "$source_dir")
+  done
+
+  # Generate HTML and XML reports.
+  xml_report=$REPORT_PLATFORM_DIR/index.xml
+  java -jar /opt/jacoco-cli.jar report $jacoco_merged_exec \
+      --html $REPORT_PLATFORM_DIR \
+      --xml $xml_report \
+      --classfiles $classes_dir \
+      "${sourcefiles_args[@]}"
+
+  # Write llvm-cov summary file.
+  jacoco_report_converter.py $xml_report $SUMMARY_FILE
+
+  set +e
 else
 
   # From this point on the script does not tolerate any errors.
@@ -205,6 +303,10 @@ else
       -output-dir=$REPORT_ROOT_DIR $PATH_EQUIVALENCE_ARGS
 
 fi
+
+# Make sure report is readable.
+chmod -R +r $REPORT_ROOT_DIR
+find $REPORT_ROOT_DIR -type d -exec chmod +x {} +
 
 if [[ -n $HTTP_PORT ]]; then
   # Serve the report locally.
diff --git a/system/update_engine/scripts/brillo_update_payload b/system/update_engine/scripts/brillo_update_payload
--- a/system/update_engine/scripts/brillo_update_payload
+++ b/system/update_engine/scripts/brillo_update_payload
@@ -38,6 +38,8 @@
 #  --disable_fec_computation  Disable the on device fec data computation for
 #                             incremental update. This feature is enabled by
 #                             default
+#  --force_minor_version      Override the minor version used for delta
+#                             generation.
 #
 #  Hash command arguments:
 #  --unsigned_payload    the input unsigned payload to generate the hash from
@@ -204,6 +206,20 @@ a subset of partitions on device."
   DEFINE_string full_boot "" "Will include full boot image"
   DEFINE_string disable_vabc "" \
     "Optional: Disables Virtual AB Compression when installing the OTA"
+  DEFINE_string enable_vabc_xor "" \
+    "Optional: Enable the use of Virtual AB Compression XOR feature"
+  DEFINE_string force_minor_version "" \
+    "Optional: Override the minor version for the delta generation."
+  DEFINE_string compressor_types "" \
+    "Optional: allowed compressor types. Colon separated, allowe values are bz2 and brotli"
+  DEFINE_string enable_zucchini "" \
+    "Optional: Whether to enable zucchini diffing"
+  DEFINE_string enable_lz4diff "" \
+    "Optional: Whether to enable lz4 diffing for EROFS"
+  DEFINE_string liblz4_path "" \
+    "Required if --enabled_lz4diff true is passed. Path to liblz4.so. delta_generator will use this copy of liblz4.so for compression. It is important that this copy of liblz4.so is the same as the one on source build."
+  DEFINE_string erofs_compression_param "" \
+    "Compression parameter passed to mkfs.erofs's -z option."
 fi
 if [[ "${COMMAND}" == "hash" || "${COMMAND}" == "sign" ]]; then
   DEFINE_string unsigned_payload "" "Path to the input unsigned payload."
@@ -547,6 +563,9 @@ using payload minor version 2"
     # old updater.
     FORCE_MINOR_VERSION=$(read_option_uint "${ue_config}" \
       "PAYLOAD_MINOR_VERSION" 2)
+    if [[ -n "${FLAGS_force_minor_version}" ]]; then
+      FORCE_MINOR_VERSION="${FLAGS_force_minor_version}"
+    fi
     FORCE_MAJOR_VERSION=$(read_option_uint "${ue_config}" \
       "PAYLOAD_MAJOR_VERSION" 2)
 
@@ -708,6 +727,31 @@ cmd_generate() {
       GENERATOR_ARGS+=(
         --disable_verity_computation="${FLAGS_disable_verity_computation}" )
     fi
+    if [[ -n "${FLAGS_compressor_types}" ]]; then
+      GENERATOR_ARGS+=(
+        --compressor_types="${FLAGS_compressor_types}" )
+    fi
+    if [[ -n "${FLAGS_enable_zucchini}" ]]; then
+      GENERATOR_ARGS+=(
+        --enable_zucchini="${FLAGS_enable_zucchini}" )
+    fi
+    if [[ -n "${FLAGS_enable_lz4diff}" ]]; then
+      if [[ "${FLAGS_enable_lz4diff}" == "true" && -z "${FLAGS_liblz4_path}" ]]; then
+        echo "--liblz4_path is required when enable_lz4diff is set to true."
+        exit 1
+      fi
+      GENERATOR_ARGS+=(
+        --enable_lz4diff="${FLAGS_enable_lz4diff}" )
+    fi
+    if [[ -n "${FLAGS_erofs_compression_param}" ]]; then
+      GENERATOR_ARGS+=(
+        --erofs_compression_param="${FLAGS_erofs_compression_param}" )
+    fi
+  fi
+
+  if [[ -n "${FLAGS_enable_vabc_xor}" ]]; then
+    GENERATOR_ARGS+=(
+      --enable_vabc_xor="${FLAGS_enable_vabc_xor}" )
   fi
 
   if [[ -n "${FLAGS_disable_vabc}" ]]; then
@@ -754,7 +798,11 @@ cmd_generate() {
   fi
 
   echo "Running delta_generator with args: ${GENERATOR_ARGS[@]}"
-  "${GENERATOR}" "${GENERATOR_ARGS[@]}"
+  if [[ -n "${FLAGS_enable_lz4diff}" ]]; then
+    LD_PRELOAD=${LD_PRELOAD}:${FLAGS_liblz4_path} "${GENERATOR}" "${GENERATOR_ARGS[@]}"
+  else
+    "${GENERATOR}" "${GENERATOR_ARGS[@]}"
+  fi
 
   echo "Done generating ${payload_type} update."
 }
