android-11.0.0_r1

diff --git a/kernel/build/abi/bootstrap b/kernel/build/abi/bootstrap
--- a/kernel/build/abi/bootstrap
+++ b/kernel/build/abi/bootstrap
@@ -14,11 +14,14 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-ABIGAIL_VERSION=1.6
+ELFUTILS_VERSION=elfutils-0.178
+ABIGAIL_VERSION=4752d416
 
 NUM_CORES=$(cat /proc/cpuinfo | grep -c proc)
 BASE_DIR=$(readlink -f $(dirname $0))
 OUT_DIR="${BASE_DIR}/abigail-inst/${ABIGAIL_VERSION}"
+
+ELFUTILS_SRC="${BASE_DIR}/elfutils-src"
 LIBABIGAIL_SRC="${BASE_DIR}/abigail-src"
 
 # Check output dir.
@@ -27,21 +30,64 @@ if [ -e "${OUT_DIR}" ]; then
   read
 fi
 
+# Clear out the OUT_DIR
+rm -rf "${OUT_DIR}"
+
+# Add the future PATHs to the environment for the builds to pick up
+export PATH="${OUT_DIR}/bin:${PATH}"
+export LD_LIBRARY_PATH="${OUT_DIR}/lib:${OUT_DIR}/lib/elfutils:${LD_LIBRARY_PATH}"
+
+PACKAGES="autoconf libtool libxml2-dev pkg-config python3"
+# Install the dependencies.
+if ! ( hash dpkg 2>/dev/null ); then
+    echo "WARN: not running on a Debian compatible system!"
+    echo "      Please be sure you have the required packages installed on"
+    echo "      your system before continuing."
+    echo ""
+    echo "      The list of required packages is, at the minimum:"
+    echo "        ${PACKAGES}"
+    echo "      but some distributions may require more."
+    echo "      You are on your own here, be careful."
+    echo ""
+    echo "Press enter to continue or Ctrl-C to abort."
+    read
+elif ! dpkg -s ${PACKAGES} > /dev/null 2>&1 ; then
+    set -x
+    sudo apt-get install --yes ${PACKAGES}
+fi
 set -x
 
-PACKAGES="libxml2-dev elfutils libdw-dev"
-# Install the dependencies.
-if ! dpkg -s ${PACKAGES} > /dev/null 2>&1 ; then
-    sudo apt-get install ${PACKAGES}
+# Acquire elfutils sources
+if [ ! -d "${ELFUTILS_SRC}" ]; then
+  git clone git://sourceware.org/git/elfutils.git "${ELFUTILS_SRC}"
+else
+  git -C ${ELFUTILS_SRC} fetch
 fi
 
+git -C ${ELFUTILS_SRC} checkout ${ELFUTILS_VERSION}
+
+# Build elfutils
+pushd "${ELFUTILS_SRC}"
+  #git clean -dfx
+  autoreconf -i --force
+  mkdir -p build/
+  pushd build/
+    ../configure --prefix="${OUT_DIR}"    \
+                 --enable-maintainer-mode \
+                 --disable-debuginfod
+    make -j${NUM_CORES}
+    make -j${NUM_CORES} install
+  popd
+popd
+
+# Acquire libabigail sources
 if [ ! -d "${LIBABIGAIL_SRC}" ]; then
   git clone git://sourceware.org/git/libabigail.git "${LIBABIGAIL_SRC}"
 else
   git -C ${LIBABIGAIL_SRC} fetch
 fi
 
-git -C ${LIBABIGAIL_SRC} checkout libabigail-${ABIGAIL_VERSION}
+git -C ${LIBABIGAIL_SRC} checkout ${ABIGAIL_VERSION}
 
 # Build libabigail
 pushd "${LIBABIGAIL_SRC}"
@@ -49,9 +95,14 @@ pushd "${LIBABIGAIL_SRC}"
   autoreconf -i --force
   mkdir -p build/
   pushd build/
-    ../configure --prefix="${OUT_DIR}" --enable-cxx11=yes --disable-shared
-#    make -j${NUM_CORES}
-    make -j${NUM_CORES} install-exec
+    ../configure VERSION_SUFFIX="-${ABIGAIL_VERSION}-android" \
+                 --prefix="${OUT_DIR}"                        \
+                 --enable-cxx11=yes                           \
+                 --disable-shared                             \
+                 "CPPFLAGS=-I${OUT_DIR}/include"              \
+                 "LDFLAGS=-L${OUT_DIR}/lib"
+    make -j${NUM_CORES}
+    make -j${NUM_CORES} install
   popd
 popd
 
@@ -61,5 +112,6 @@ echo
 echo "Note: Export following environment before running the executables:"
 echo
 echo "export PATH=\"${OUT_DIR}/bin:\${PATH}\""
+echo "export LD_LIBRARY_PATH=\"${OUT_DIR}/lib:${OUT_DIR}/lib/elfutils:\${LD_LIBRARY_PATH}\""
 echo
 echo
