android-9.0.0_r3

diff --git a/external/devlib/devlib/bin/scripts/shutils.in b/external/devlib/devlib/bin/scripts/shutils.in
--- a/external/devlib/devlib/bin/scripts/shutils.in
+++ b/external/devlib/devlib/bin/scripts/shutils.in
@@ -187,6 +187,62 @@ cgroup_trace_attach_task() {
         done
 }
 
+cgroups_freezer_set_state() {
+    STATE=${1}
+    SYSFS_ENTRY=${2}/freezer.state
+
+    # Set the state of the freezer
+    echo $STATE > $SYSFS_ENTRY
+    
+    # And check it applied cleanly
+    for i in `seq 1 10`; do
+        [ $($CAT $SYSFS_ENTRY) = $STATE ] && exit 0
+        sleep 1
+    done
+
+    # We have an issue
+    echo "ERROR: Freezer stalled while changing state to \"$STATE\"." >&2
+    exit 1
+}
+
+################################################################################
+# Hotplug
+################################################################################
+
+hotplug_online_all() {
+    for path in /sys/devices/system/cpu/cpu[0-9]*; do
+        if [ $(cat $path/online) -eq 0 ]; then
+            echo 1 > $path/online
+        fi
+    done
+}
+
+################################################################################
+# Misc
+################################################################################
+
+read_tree_values() {
+    BASEPATH=$1
+    MAXDEPTH=$2
+
+    if [ ! -e $BASEPATH ]; then
+        echo "ERROR: $BASEPATH does not exist"
+        exit 1
+    fi
+
+    PATHS=$($BUSYBOX find $BASEPATH -follow -maxdepth $MAXDEPTH)
+    i=0
+    for path in $PATHS; do
+        i=$(expr $i + 1)
+        if [ $i -gt 1 ]; then
+            break;
+        fi
+    done
+    if [ $i -gt 1 ]; then
+        $BUSYBOX grep -s '' $PATHS
+    fi
+}
+
 ################################################################################
 # Main Function Dispatcher
 ################################################################################
@@ -225,8 +281,17 @@ cgroups_tasks_move)
 cgroups_tasks_in)
 	cgroups_tasks_in $*
 	;;
+cgroups_freezer_set_state)
+	cgroups_freezer_set_state $*
+	;;
 ftrace_get_function_stats)
     ftrace_get_function_stats
+    ;;
+hotplug_online_all)
+	hotplug_online_all
+    ;;
+read_tree_values)
+	read_tree_values $*
     ;;
 *)
     echo "Command [$CMD] not supported"
diff --git a/external/lisa/src/shell/lisa_shell b/external/lisa/src/shell/lisa_shell
--- a/external/lisa/src/shell/lisa_shell
+++ b/external/lisa/src/shell/lisa_shell
@@ -121,7 +121,11 @@ if [ $ret -ne 0 ]; then
 fi
 
 curr_commit=$(git rev-parse HEAD)
-remote_name=$(git remote -v | grep ARM-software/lisa | grep -m 1 fetch | awk '{print $1}')
+remote_name=$(git remote -v | grep -i ARM-software/lisa | grep -m 1 fetch | awk '{print $1}')
+if [ -z "$remote_name" ]; then
+    echo "Couldn't find ARM-Software upstream remote, can't automatically update"
+    return 1
+fi
 git merge-base --is-ancestor $curr_commit $remote_name/master
 ret=$?
 if [ $ret -ne 0 ]; then
@@ -283,26 +287,39 @@ fi
 
 function _lisa-test-usage {
 cat <<EOF
-Usage: lisa-test [args] FILE[:CLASS]
+Usage: lisa-test [--iterations ITERATIONS] [args] FILE[:CLASS]
   Run automated tests. Tests can be found under the tests/ directory.
+
+  --iterations (or -n) sets the number of iterations to use for
+    each workload/target-conf, for tests that support this usage. 0 means use
+    the test's default iteration count.
 
   This is a wrapper for the 'nosetests' utility, additional arguments are passed
   to that tool.
 
   Examples:
-    Run all EAS Acceptance tests:
+    Run all EAS Generic tests:
 
-      lisa-test tests/eas/acceptance.py
+      lisa-test tests/eas/generic.py
 
-    Run ForkMigration test from EAS Acceptance suite:
+    Run RampUp test from EAS Generic suite:
 
-      lisa-test tests/eas/acceptance.py:ForkMigration
+      lisa-test tests/eas/generic.py:RampUp
 
-    Run ForkMigration test from EAS Acceptance suite, generating an XML test
+    Run RampUp test from EAS Generic suite, generating an XML test
     report via nose's XUnit plugin (see nosetests documentation):
 
-      lisa-test --with-xunit --xunit-file=report.xml tests/eas/acceptance.py:ForkMigration
+      lisa-test --with-xunit --xunit-file=report.xml tests/eas/generic.py:RampUp
 
+    Run RampUp test from EAS Generic suite, repeating the
+    workload 10 times and reporting how many times the test run
+    passed:
+
+      lisa-test --iterations 10 tests/eas/generic.py:RampUp
+
+    Run EAS Generic suite, repeating each workload 10 times:
+
+      lisa-test --iterations 10 tests/eas/generic.py
 EOF
 }
 
@@ -313,16 +330,36 @@ nosetests -v --nocapture --nologcapture \
 }
 
 function lisa-test {
-CMD=${1:-help}
+local iterations=0 # Means use default - see libs/utils/test.py
+local extra_args=""
+
 echo
-case "x${CMD^^}" in
-"xHELP")
-	_lisa-test-usage
-	;;
-*)
-	_lisa-test $*
-        local retcode=$?
-esac
+while [[ $# -gt 0 ]]; do
+        case "$1" in
+                help|-h|--help)
+                        _lisa-test-usage
+                        return 0
+                        ;;
+                -n|--iterations)
+                        iterations="$2"
+                        shift
+                        ;;
+                *)
+                        # Unrecognised args are passed through to nosetests
+                        extra_args="$extra_args $1"
+                        ;;
+        esac
+        shift
+done
+
+if [ -z "$extra_args" ]; then
+        # No arguments provided, default to "help"
+        _lisa-test-usage
+        return 1
+fi
+
+(export LISA_TEST_ITERATIONS=$iterations; _lisa-test $extra_args)
+local retcode=$?
 echo
 echo
 return $retcode
diff --git a/test/vts/tools/vts-tradefed/etc/vts-tradefed b/test/vts/tools/vts-tradefed/etc/vts-tradefed
--- a/test/vts/tools/vts-tradefed/etc/vts-tradefed
+++ b/test/vts/tools/vts-tradefed/etc/vts-tradefed
@@ -16,6 +16,16 @@
 
 # launcher script for vts-tradefed harness
 # can be used from an Android build environment, or a standalone vts zip
+#
+# Usage:
+#   # to test a device with system.img = v9.0 and vendor.img = v9.0
+#       $ vts-tradefed
+#
+#   # to test a device with system.img = v9.0 and vendor.img = v8.1
+#       $ vts-tradefed -v=8.1
+#
+#   # all other cases are unsupported
+#
 
 checkFile() {
     if [ ! -f "$1" ]; then
@@ -35,18 +45,10 @@ checkPath adb
 checkPath java
 
 # check java version
-if [ "${EXPERIMENTAL_USE_OPENJDK9}" == "" ]; then
-    JAVA_VERSION=$(java -version 2>&1 | head -n 2 | grep '[ "]1\.[678][\. "$$]')
-    if [ "${JAVA_VERSION}" == "" ]; then
-        echo "Wrong java version. 1.6, 1.7 or 1.8 is required."
-        exit
-    fi
-else
-    JAVA_VERSION=$(java -version 2>&1 | head -n 2 | grep '^java .* "9.*')
-    if [ "${JAVA_VERSION}" == "" ]; then
-        echo "Wrong java version. Version 9 is required."
-        exit
-    fi
+JAVA_VERSION=$(java -version 2>&1 | head -n 1 | grep 'version [ "]\(1\.8\|9\).*[ "]')
+if [ "${JAVA_VERSION}" == "" ]; then
+    echo "Wrong java version. 1.8 or 9 is required."
+    exit
 fi
 
 # check debug flag and set up remote debugging
@@ -86,16 +88,32 @@ if [ -z ${VTS_ROOT} ]; then
     VTS_ROOT="$(dirname $(readlink -e $0))/../.."
 fi;
 
-JAR_DIR=${VTS_ROOT}/android-vts/tools
+VTS_JAR_DIR=${VTS_ROOT}/android-vts/tools
+STANDALONE_JAR_DIR=${ANDROID_HOST_OUT}/framework
+JAR_DIRS="$VTS_JAR_DIR
+  $STANDALONE_JAR_DIR"
 
+JAR_DIR=""
+# Wherever we find the tradefed jar is where we expect the other jars to be.
 TRADEFED_JAR="tradefed"
-if [ ! -f ${JAR_DIR}/${TRADEFED_JAR}.jar ]; then
+for CHECK_JAR_DIR in $JAR_DIRS; do
+  if [ -f ${CHECK_JAR_DIR}/${TRADEFED_JAR}.jar ]; then
+    JAR_DIR=$CHECK_JAR_DIR
+    break
+  fi;
+done
+
+# If we didn't find the TF jar, resort to tf prebuilt in VTS_JAR_DIR.
+if [ -z $JAR_DIR ]; then
+  JAR_DIR=$VTS_JAR_DIR
   TRADEFED_JAR="tradefed-prebuilt"
-fi;
+fi
 
 JARS="${TRADEFED_JAR}
+  loganalysis
   hosttestlib
   vts-tradefed
+  vts-tradefed-tests
   compatibility-host-util"
 
 for JAR in $JARS; do
@@ -108,13 +126,17 @@ OPTIONAL_JARS="
   android-vts/tools/google-tradefed-vts-prebuilt
   google-tradefed-prebuilt
   google-tradefed-tests
-  google-tf-prod-tests"
+  google-tf-prod-tests
+  google-tradefed"
 
 for JAR in $OPTIONAL_JARS; do
-    if [ -f "${VTS_ROOT}/${JAR}.jar" ]; then
-        echo "Including optional JAR: $VTS_ROOT/$JAR.jar"
-        JAR_PATH=${JAR_PATH}:${VTS_ROOT}/${JAR}.jar
-    fi;
+    for OPT_JAR_DIR in $VTS_ROOT $JAR_DIR; do
+        if [ -f "${OPT_JAR_DIR}/${JAR}.jar" ]; then
+            echo "Including optional JAR: ${OPT_JAR_DIR}/${JAR}.jar"
+            JAR_PATH=${JAR_PATH}:${OPT_JAR_DIR}/${JAR}.jar
+            break
+        fi;
+    done
 done
 
 # load any shared libraries for host-side executables
@@ -132,4 +154,30 @@ for j in ${VTS_ROOT}/android-vts/testcases/*.jar; do
     JAR_PATH=${JAR_PATH}:$j
 done
 
-cd ${VTS_ROOT}/android-vts/testcases/; java $RDBG_FLAG -cp ${JAR_PATH} -DVTS_ROOT=${VTS_ROOT} com.android.compatibility.common.tradefed.command.CompatibilityConsole "$@"
+ARGS=()
+for var in "$@"
+do
+case $var in
+    -v=*|--vendor-image=*)
+    VENDOR="${var#*=}"
+    if [ "${VENDOR}" == "9.0" ]; then
+        VENDOR=""
+    elif [ "${VENDOR}" != "8.1" ]; then
+        echo "Supports only --vendor-image=8.1."
+        echo "By default, 9.0 is the supported vendor.img version."
+        exit 1
+    fi
+    ;;
+    *)
+    ARGS+=("$var")
+    ;;
+esac
+done
+
+if [ -z "${VENDOR}" ]; then
+    VTS_TESTCASES=${VTS_ROOT}/android-vts/testcases/
+else
+    VTS_TESTCASES=${VTS_ROOT}/android-vts/${VENDOR}/testcases/
+fi
+
+cd ${VTS_TESTCASES}; VTS_TESTCASES=${VTS_TESTCASES} java $RDBG_FLAG -cp ${JAR_PATH} -DVTS_ROOT=${VTS_ROOT} com.android.compatibility.common.tradefed.command.CompatibilityConsole "${ARGS[@]}"
